### ISSUE TITLE
Define node.js version for the dashboard project 

### ISSUE THREAD

**Issue by shivam-sharma7** [tailwarden/komiser#1008]
**Is your feature request related to a problem? Please describe.**
`.nvmrc ` file a simple string representing the version of Node.js the project requires. As we know lot of depreciation comming with new node 20 LTS and we need to make sure which version we are using for our dashboard.

**Comment by Traxmaxx** [comment]
Heya, thanks a lot for the recommendation. Having a `.nvmrc` is a great idea!

Enforcing the node version is done via package.json though. There should be an `engines` [entry](https://docs.npmjs.com/cli/v10/configuring-npm/package-json?v=true#engines).

The benefit of having both is, if someone is using [node-env](https://github.com/nodenv/nodenv) or [asdf-vm](https://asdf-vm.com/) they receive an warning like this when running `npm install`:

```logtalk
~/S/t/k/dashboard > npm install                                                                                                                                                                                                           
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'komiser-dashboard@3.1.0',
npm WARN EBADENGINE   required: { node: '20.0.7' },
npm WARN EBADENGINE   current: { node: 'v18.16.1', npm: '9.5.1' }
npm WARN EBADENGINE }
```

If we would just go with the `.nvmrc` everyone without NVM would never know what version is actually required and can potentially submit invalid code.

**Comment by shivam-sharma7** [comment]
> Heya, thanks a lot for the recommendation. Having a `.nvmrc` is a great idea!
> 
> Enforcing the node version is done via package.json though. There should be an `engines` [entry](https://docs.npmjs.com/cli/v10/configuring-npm/package-json?v=true#engines).
> 
> The benefit of having both is, if someone is using [node-env](https://github.com/nodenv/nodenv) or [asdf-vm](https://asdf-vm.com/) insted of NVM they receive an warning when running `npm install`:
> 
> ```logtalk
> ~/S/t/k/dashboard > npm install                                                                                                                                                                                                           
> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: 'komiser-dashboard@3.1.0',
> npm WARN EBADENGINE   required: { node: '20.0.7' },
> npm WARN EBADENGINE   current: { node: 'v18.16.1', npm: '9.5.1' }
> npm WARN EBADENGINE }
> ```
> 
I'm not agree with the above thing because we don't want to create any restriction for the development side, having `.nvmrc` would be good enough, defining following thing is for project like- buiilding npm packages, cli tools and  stuff not for this project.

{
  "engines": {
    "node": ">=0.10.3 <15"
  }
}

**Comment by shivam-sharma7** [comment]
@Traxmaxx Okay

I know that komiser never should be static so we don't care about node.js version and we are building dashboard not the thing what I mentioned above we are going to adopt every new tech stack what make komiser better from design wise and develepment wise as well.This would be a concern if we used Node for the backend.
