### ISSUE TITLE
Cloud provider logos consistency

### ISSUE THREAD

**Issue by AllieMendes** [tailwarden/komiser#1010]
**Describe the issue**
Currently, there are a few inconsistencies on the cloud provider logos, namely the file type (some are PNGs, others JPGs - for example) and not using the images from the design files.

**Proposed solution**
Sync all the cloud provider logos by exporting the logos from the Figma designs, all in the same format and size, and replacing the current ones on the Komiser platform.
![image](https://github.com/tailwarden/komiser/assets/125025039/676efd71-e693-41f6-881e-c1884f72bf16)

Additional context
If you want to tackle this task, feel free to share with us your email address so we can give you access to the Figma project :)

**Comment by shivam-sharma7** [comment]
@AllieMendes I would look into this

**Comment by Jittojoyes98** [comment]
Hey, new here can I take this up ?

**Comment by AllieMendes** [comment]
Hey @Jittojoyes98!
Of course, thank you for jumping in
Can you tell me which email I should invite to the Figma file?

**Comment by AllieMendes** [comment]
> @AllieMendes you can mail me here : [jittojoyes77@gmail.com](mailto:jittojoyes77@gmail.com)

Great! I've sent an invitation
You can find the cloud provider logos on the Avatars page, just select the image layer and export it on the right side panel
Feel free to tag me on Figma or here if you have any questions

**Comment by Jittojoyes98** [comment]
Give me some time to figure out, will keep you posted.

**Comment by AllieMendes** [comment]
Closed as this issue has been addressed on #1097
