### ISSUE TITLE
DigitalOcean is not bringing the cost of volumes.

### ISSUE THREAD

**Issue by edxz101** [tailwarden/komiser#1020]
Hi team,
DigitalOcean integration is not bringing the cost of volumes.
I'm using Docker version.

<img width="1321" alt="Captura de pantalla 2023-10-02 a la(s) 22 39 19" src="https://github.com/tailwarden/komiser/assets/2080750/bbefdefe-d893-466f-9995-ed10c68dc3c1">

**Comment by jakepage91** [comment]
Hey there @edxz101 thanks for opening the issue! At the moment we don't support cost calculation for volumes. I also realised that we don't have an open issue for that (which I'll open now.) It looks like only droplets have cost calculation supported. Which other DigitalOcean services would you like us to prioritise apart from volumes?

**Comment by jakepage91** [comment]
Thanks a million for the feedback @edxz101 it's super helpful. 

- In regards to the DigitalOcean volumes cost issue! I'm going to flesh out a description on this issue and I'm also going to slap on a `hacktoberfest` tag to the issue so we can potentially get a contributor on it asap. 
- Regarding the estimated monthly cost, let me check with the maintainers and team to see how we can include this asap.
- At the time being we are pushing hard to first fully cover AWS cost, once AWS cost coverage is complete we will move onto GCP
- This last item is strange unless you are usingthe `--regions` flag and passing in a specific region, all supported services (in this case MySql instances are supported) should appear. I will have to test this out locally to see if I can recreate the behaviour. I will be reporting back to you shortly on this one.

Thanks again.

**Comment by jakepage91** [comment]
Hey there @edxz101 just realised that I have opened this [issue](https://github.com/tailwarden/komiser/issues/1048) (supporting cost for DigitalOcean volumes) will update here once it's done!

**Comment by edxz101** [comment]
@jakepage91 I Attach a print of GCP SQL Instance bug.

<img width="1139" alt="Captura de pantalla 2023-10-12 a la(s) 11 31 46" src="https://github.com/tailwarden/komiser/assets/2080750/9f2dd369-aa11-41de-8f25-76e79aedeeed">
<img width="1317" alt="Captura de pantalla 2023-10-12 a la(s) 11 35 10" src="https://github.com/tailwarden/komiser/assets/2080750/1f6d7bb6-c47e-4e93-becf-f1d7519ff1ae">

**Comment by jakepage91** [comment]
Here it is, now that it's been given the `hacktoberfest` label hopefully it will get picked up. https://github.com/tailwarden/komiser/issues/777

**Comment by Azanul** [comment]
@jakepage91 I think this an also be closed
