### ISSUE TITLE
Cost calculations for AWS EC2 is either missing or incorrect

### ISSUE THREAD

**Issue by mlabouardy** [tailwarden/komiser#1021]
## Describe the solution you'd like

A checklist for cost calculation of each resource
- [ ] Fetch price info using AWS SDK price module using `AmazonEC2` service code and appropriate filters.
- [ ] Get flat price map using util function `GetPriceMap` from [utils.go](https://github.com/tailwarden/komiser/blob/develop/providers/aws/utils/utils.go)
- [ ] Using EC2 client fetch the resource objects [Docs AWS service Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/EC2/)
- [ ] Fetch usage metrics using AWS SDK cloudwatch module [AWS usage metrics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Service-Quota-Integration.html) [EC2 metrics](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html)
- [ ] Calculate the cost according to EC2 AWS documentation [Link to AWS EC2 pricing](https://aws.amazon.com/ec2/pricing/)

For inspiration take a look at [AWS Lambda](https://github.com/tailwarden/komiser/blob/develop/providers/aws/lambda/functions.go)

**Comment by YashPimple** [comment]
Heyy @mlabouardy I would like to work on the issue

**Comment by mlabouardy** [comment]
> Heyy @mlabouardy I would like to work on the issue

all yours :)

**Comment by ShubhamPalriwala** [comment]
hey @YashPimple how's it going? anything that we can help with?

**Comment by YashPimple** [comment]
> hey @YashPimple how's it going? anything that we can help with?

Hey @ShubhamPalriwala currently i have started woking on it and if any doubts arise, I'll be sure to ping you. Thanks!

**Comment by Prasad971** [comment]
Hey @mlabouardy i would like to contribute can you please assign.
Thanks.

**Comment by bishal7679** [comment]
@AvineshTripathi @mlabouardy PHAL here!

**Comment by bishal7679** [comment]
@jakepage91 @AvineshTripathi PHAL here!
Hey @YashPimple Are you still working on it??
As this issue is getting stale shouldn't we assign it to @Prasad971 might be interested!

**Comment by YashPimple** [comment]
> @jakepage91 @AvineshTripathi PHAL here! Hey @YashPimple Are you still working on it?? As this issue is getting stale shouldn't we assign it to @Prasad971 might be interested!

Sure @bishal7679 I would be able to work on these due to Kubecon so assigning it to @Prasad971 will be great idea.
@Prasad971, are you available to take this on?

**Comment by Prasad971** [comment]
@jakepage91 I'm available to taje this.

**Comment by bishal7679** [comment]
> > @jakepage91 @AvineshTripathi PHAL here! Hey @YashPimple Are you still working on it?? As this issue is getting stale shouldn't we assign it to @Prasad971 might be interested!
> 
> Sure @bishal7679 I would not be able to work on these due to Kubecon so assigning it to @Prasad971 will be great idea. @Prasad971, are you available to take this on?

No worries @YashPimple 
All the best for kubecon! Looking forward to your talk there
