### ISSUE TITLE
Cost calculations for AWS S3 is either missing or incorrect

### ISSUE THREAD

**Issue by mlabouardy** [tailwarden/komiser#1022]
## Describe the solution you'd like

A checklist for cost calculation of each resource
- [ ] Fetch price info using AWS SDK price module using `AmazonS3` service code and appropriate filters.
- [ ] Get flat price map using util function `GetPriceMap` from [utils.go](https://github.com/tailwarden/komiser/blob/develop/providers/aws/utils/utils.go)
- [ ] Using S3 client fetch the resource objects [Docs AWS service Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/S3/)
- [ ] Fetch usage metrics using AWS SDK cloudwatch module [AWS usage metrics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Service-Quota-Integration.html) [S3 metrics](https://docs.aws.amazon.com/AmazonS3/latest/userguide/metrics-dimensions.html)
- [ ] Calculate the cost according to S3 AWS documentation [Link to AWS S3 pricing](https://aws.amazon.com/s3/pricing/)

For inspiration take a look at [AWS Lambda](https://github.com/tailwarden/komiser/blob/develop/providers/aws/lambda/functions.go)

**Comment by bishal7679** [comment]
Hey @mlabouardy!
This is my first time contributing to komiser
such a nice tool which I came accross and exploring...
could you pls assign me this issue?
would love to give it a try :+1:

**Comment by mlabouardy** [comment]
> Hey @mlabouardy! This is my first time contributing to komiser such a nice tool which I came accross and exploring... could you pls assign me this issue? would love to give it a try 👍

all yours :)

**Comment by verma-kunal** [comment]
> Hey @mlabouardy! This is my first time contributing to komiser such a nice tool which I came accross and exploring... 

Hey @bishal7679 , glad to see you here 👋
