### ISSUE TITLE
Cost calculations for AWS RDS is either missing or incorrect

### ISSUE THREAD

**Issue by mlabouardy** [tailwarden/komiser#1023]
## Describe the solution you'd like

A checklist for cost calculation of each resource
- [ ] Fetch price info using AWS SDK price module using `AmazonRDS` service code and appropriate filters.
- [ ] Get flat price map using util function `GetPriceMap` from [utils.go](https://github.com/tailwarden/komiser/blob/develop/providers/aws/utils/utils.go)
- [ ] Using RDS client fetch the resource objects [Docs AWS service Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/RDS/)
- [ ] Fetch usage metrics using AWS SDK cloudwatch module [AWS usage metrics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Service-Quota-Integration.html) [RDS metrics](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-metrics.html)
- [ ] Calculate the cost according to RDS AWS documentation [Link to AWS RDS pricing](https://aws.amazon.com/rds/pricing/)

For inspiration take a look at [AWS Lambda](https://github.com/tailwarden/komiser/blob/develop/providers/aws/lambda/functions.go)

**Comment by VedankPande** [comment]
Hey @mlabouardy, you can assign this issue to me

**Comment by mlabouardy** [comment]
> Hey @mlabouardy, you can assign this issue to me

yours :)

**Comment by VedankPande** [comment]
@mlabouardy could you please describe what was originally wrong with the pricing?
