### ISSUE TITLE
Update contributing.md

### ISSUE THREAD

**Issue by AvineshTripathi** [tailwarden/komiser#1029]
**Is your feature request related to a problem? Please describe.**
The current contributing.md has not been touched for a long time and needs to be revisited to help new contributors get familiar with the project. 

**Describe the solution you'd like**
- We should add more detailed explaination to how the project is structured and how can an - individual run everything locally and contribute. 
- We should also write about testing things and how we can help folks with necessary env to test their code
- We also want to tell folks how they can contribute without any code(maybe talk about initiatives we have started)
- Maybe a roadmap?

**Comment by verma-kunal** [comment]
@jakepage91 would love to work on this one 😄

**Comment by jakepage91** [comment]
Nice one @verma-kunal, @AvineshTripathi thank you kindly also 🙏
