### ISSUE TITLE
Add support for Opencost cost calculation for Kubernetes services.

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#1036]
**Is your feature request related to a problem? Please describe.**
The Opencost integration currently only supports cost calculation for Pods, we would like the cost calculation done for [Kuberntes services](https://github.com/tailwarden/komiser/blob/develop/providers/k8s/core/services.go) too. 

Use this as an example of what was added to [`pods`](https://github.com/tailwarden/komiser/blob/72346a7c61c6fe2cbe6419513596f82aa59c4df4/providers/k8s/core/pods.go#L21C6-L21C6)

Opencost API reference if needed: https://www.opencost.io/docs/integrations/api

**Comment by shubhindia** [comment]
@jakepage91  Since the PR is already merged, can you please close this one.
