### ISSUE TITLE
Add suport for kubernetes Controllers and add opencost cost calculation

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#1037]
**Is your feature request related to a problem? Please describe.**
Using the [Kubernetes pods](https://github.com/tailwarden/komiser/blob/develop/providers/k8s/core/pods.go) file as an example, add support for Kubernetes controllers

Cost calculation for controllers can be added simply by following the example on [line 21 of the pods file](https://github.com/tailwarden/komiser/blob/develop/providers/k8s/core/pods.go#L21) example simply passing the `controller` field

**Comment by shubhindia** [comment]
@jakepage91 which controller exactly?

**Comment by Azanul** [comment]
> @jakepage91 which controller exactly?

Opencost aggregates costs by k8s primitives. We don't need to pass a specific controller, we want to know how much cost is each controller incurring.

**Comment by shubhindia** [comment]
There are multiple controllers. Goal is to cover all of them or just the ones which spawn pods?

**Comment by Azanul** [comment]
> There are multiple controllers. Goal is to cover all of them or just the ones which spawn pods?

The high level goal is to calculate cost. Currently we use opencost integration to do so, hence we cover all kinds that opencost covers i.e., deployment, statefulset, daemonset and job.

**Comment by asamirr** [comment]
We already have deployments implemented so we need to add 3 more files for statefulset, daemonset and job?

**Comment by asamirr** [comment]
[Discord](https://discord.com/invite/MfUy73AUyd/)

**Comment by jakepage91** [comment]
Hey there @shubhindia feel free to joing the discord server, it will for sure reduce the reponse time. So yeah, I wrote up this issue with this section of the [OpenCost API](https://www.opencost.io/docs/integrations/api#aggregate) docs in mind. As you can see we can choose between `controller` and controllerKind` but we only want to know what cost amount do all controllers incur for now, so I'm guessing that specifying the `controller` field will be enough
