### ISSUE TITLE
Add support for Kubernetes nodes + cost calculation

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#1039]
**Is your feature request related to a problem? Please describe.**
Using the [Kubernetes pods](https://github.com/tailwarden/komiser/blob/develop/providers/k8s/core/pods.go) file as an example, add support for Kubernetes nodes

Cost calculation for nodes can be added simply by following the example on [line 21 of the pods file](https://github.com/tailwarden/komiser/blob/develop/providers/k8s/core/pods.go#L21) example simply passing the `node` field 

Opencost API reference if needed: https://www.opencost.io/docs/integrations/api

**Comment by asamirr** [comment]
Would love to work on this one!
