### ISSUE TITLE
Add cost calculation for DigitalOcean volumes

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#1048]
**Is your feature request related to a problem? Please describe.**
Similar to what has been done for [Droplets](https://github.com/tailwarden/komiser/blob/develop/providers/digitalocean/droplets/droplets.go#L59), create a volume level price calculation that can be displayed in the Komiser dashboard.

**Comment by shubhampaliwal3011** [comment]
Hey, I would like to give a try to add this feature, could you please assign this to me.

**Comment by jakepage91** [comment]
All yours! @shubhampaliwal3011

**Comment by bishal7679** [comment]
@jakepage91 As this issue being stale could you pls assign it to me!
happy to solve

**Comment by bishal7679** [comment]
@jakepage91 we can close this issue as resolved by #1190
