### ISSUE TITLE
Relation name persisting on screen

### ISSUE THREAD

**Issue by AllieMendes** [tailwarden/komiser#1066]
**Describe the bug**
When zooming out while hovering on the relation between two nodes, the relation name persists even after moving the mouse, staying on screen across pages. This behavior can stack.

**To Reproduce**
1. I zoomed on the resources explorer.
2. I hovered over a relation between two nodes — the name of the relation appeared.
3. I zoomed out, keeping the mouse still unintentionally.
4. The relation caption stayed on the screen and doesn't move or disappear unless I refresh the page.

**Expected behavior**
When the zooming threshold for the resource names to be hidden is reached, the relation name should disappear as well or at least disappear if I move the mouse after zooming out.

**Screenshots**
<img width="1511" alt="Screenshot 2023-10-10 at 17 09 12" src="https://github.com/tailwarden/komiser/assets/125025039/57093b50-1d0d-4f83-98a6-af1d8dcb22e8">
<img width="1511" alt="Screenshot 2023-10-10 at 17 09 39" src="https://github.com/tailwarden/komiser/assets/125025039/cbc5c3b2-32fe-46f7-bf80-7782907ac30c">
<img width="1510" alt="Screenshot 2023-10-10 at 17 11 10" src="https://github.com/tailwarden/komiser/assets/125025039/88ab6b57-8388-4654-8488-4de82e20963d">

**Desktop**
 - OS: iOS
 - Browser Chrome
 - Version 117

**Additional context**
- The link where the bug happened: /explorer/

**Comment by faisal7008** [comment]
hi @AllieMendes i solved this issue. can you please assign this issue to me so that i can raise PR

**Comment by AvineshTripathi** [comment]
Sure @faisal7008 issue is all yours
