### ISSUE TITLE
Show navigation and zoom utilities in Resources Explorer

### ISSUE THREAD

**Issue by AllieMendes** [tailwarden/komiser#1070]
**Task**
We would like to show a slider for the current zoom level and allow users to disable node dragging temporarily. We unfortunately need to build this ourselves. There is an addon for Cytoscape [here](https://github.com/cytoscape/cytoscape.js-panzoom) but unfortunately it's built with jQuery in mind and we rather do not want to pull in a jQuery dependency for obvious reasons. The zoom level can be read inside cyActionHandlers in /komiser/dashboard/components/explorer/DependencyGraph.tsx:50 and should be stored inside a state variable. This could be done inside cy.on('zoom', event => { but needs to be performance tested. It's probably a good idea to debounce state updates to keep the rendering performance snappy! 

Our average assumption of infrastructure sizes of our customers is within the range of 500 to 50k of nodes/services so please keep that in mind.

<img width="1065" alt="image" src="https://github.com/tailwarden/komiser/assets/125025039/82b95a3e-386e-4302-b977-d05b8ab07d22">

**Additional context**
If you want to tackle this task, feel free to share with us your email address so we can give you access to the Figma project :)

**Comment by faisal7008** [comment]
hey @AllieMendes I started working on this. Can you assign this to me ?

**Comment by faisal7008** [comment]
Hey @AllieMendes the zoom percentage here, is it input type ?
Also, how should the drag button look when the user disables the node dragging?

**Comment by faisal7008** [comment]
> Hey @AllieMendes the zoom percentage here, is it input type ? Also, how should the drag button look when the user disables the node dragging?

hey @AllieMendes @Traxmaxx @mlabouardy 
someone clear this doubt for me, i've implemented it, waiting to raise PR

**Comment by Traxmaxx** [comment]
Hey @faisal7008 We are all at a offsite at the moment and I will get back to you tomorrow. Sorry for letting you wait!

**Comment by AllieMendes** [comment]
Hey @faisal7008! That input hasn't been implemented yet, so maybe we would need to add it to storybook first — what do you think @Traxmaxx?
Regarding the zoom percentage, it would be an input type, yes, so the user can choose to write the number, use the buttons or scroll with the mouse wheel
I'll add an active state to the button on the DS so that case is covered, thank you for mentioning it

**Comment by AllieMendes** [comment]
I've added the active state of the button to the DS, synced the sizes to match what's to be implemented and supposed usage, and added a screen to the Resources Explorer designs to showcase the active state of the drag-hand button
Hope this helps @faisal7008!

**Comment by faisal7008** [comment]
Hey @AllieMendes , could you please share figma access to faisalhussain7008@gmail.com? I currently have access to the UI components, but I'm unable to view the page designs.

**Comment by faisal7008** [comment]
> I've added the active state of the button to the DS, synced the sizes to match what's to be implemented and supposed usage, and added a screen to the Resources Explorer designs to showcase the active state of the drag-hand button Hope this helps @faisal7008!

Thanks @AllieMendes 

Could you please share figma access to [faisalhussain7008@gmail.com](mailto:faisalhussain7008@gmail.com)? I currently have access to the UI components, but I'm unable to view the page designs.

**Comment by AllieMendes** [comment]
Of course, I've sent an invitation

> > I've added the active state of the button to the DS, synced the sizes to match what's to be implemented and supposed usage, and added a screen to the Resources Explorer designs to showcase the active state of the drag-hand button Hope this helps @faisal7008!
> 
> Thanks @AllieMendes
> 
> Could you please share figma access to [faisalhussain7008@gmail.com](mailto:faisalhussain7008@gmail.com)? I currently have access to the UI components, but I'm unable to view the page designs.

Of course, I've sent an invitation
