### ISSUE TITLE
Empty state for Explorer (filters)

### ISSUE THREAD

**Issue by AllieMendes** [tailwarden/komiser#1079]
**Feature description**
Currently, when the results for the filters applied on the Resources Explorer page are empty, the page renders an empty canvas.
The goal is to implement the empty state covered on the designs so it's more clear there are no results for the filters selected.

![image](https://github.com/tailwarden/komiser/assets/125025039/bc7f1968-0899-4b19-9ed1-0e63434fcd80)

**Additional context**
If you want to tackle this task, feel free to share with us your email address so we can give you access to the Figma project :)

**Comment by shavidze** [comment]
Let me take this.
`gmail`: `sabashavidze@gmail.com`

**Comment by shavidze** [comment]
[__Related PL__](https://github.com/tailwarden/komiser/pull/1096)
