### ISSUE TITLE
Empty state for Explorer (no resources)

### ISSUE THREAD

**Issue by AllieMendes** [tailwarden/komiser#1081]
**Feature description**
Currently, when there are no (AWS) resources on the cloud accounts connected, the Explorer renders an empty canvas.
The goal is to implement the empty state covered on the designs so it's users can know the Explorer is working correctly, just that there are no resources to be displayed.

![image](https://github.com/tailwarden/komiser/assets/125025039/48b7ea22-13cf-478c-ab37-754417f07c80)

**Additional context**
If you want to tackle this task, feel free to share with us your email address so we can give you access to the Figma project :)

**Comment by umrkhn** [comment]
@AllieMendes I would like to work on this issue.

**Comment by Azanul** [comment]
@umrkhn There you go! feel free to reach out on [our Discord server](https://discord.tailwarden.com/) if you face any issues and need help.

**Comment by AllieMendes** [comment]
Thank you for reaching out @umrkhn! Do you have an email I can use to invite you to Figma so you check the designs?
