### ISSUE TITLE
Update color names and box-shadows to be consistent with Figma

### ISSUE THREAD

**Issue by Traxmaxx** [tailwarden/komiser#1092]
Update colors in either Figma or Tailwind to have matching names. Please sync with @AllieMendes before starting this task!
Also to check as part of this task are box-shadows

Figma design for box-hadows can be found here:
https://www.figma.com/file/eq3JgvmW48IVrYcg2kzgLL/Komiser---Design-System?type=design&node-id=2085-14866&mode=dev

Colors are here:
https://www.figma.com/file/eq3JgvmW48IVrYcg2kzgLL/Komiser---Design-System?type=design&node-id=2825-13629&mode=dev

Our colors are defined inside `komiser/dashboard/tailwind.config.js:1`

```json
      colors: {
        primary: '#008484',
        secondary: '#065555',
        komiser: {
          100: '#F5FDFD',
          120: '#e5f8f8',
          130: '#E2F6F6',
          150: '#DFF5F5',
          200: '#CCF2F2',
          300: '#99E5E5',
          400: '#66D9D9',
          500: '#33CCCC',
          600: '#008484',
          700: '#065555'
        },
        info: {
          600: '#387BEB'
        },
        warning: {
          100: '#FFF5DA',
          600: '#EDC16B'
        },
        error: {
          100: '#FFE8E8',
          600: '#DE5E5E',
          700: '#ae4242',
          900: '#362033'
        },
        success: {
          100: '#E1FFE3',
          600: '#56BA5B'
        },
        black: {
          100: '#F4F9F9',
          130: '#F4F2F7',
          150: '#F5F5F5',
          170: '#EDEBEE',
          200: '#CFD7D7',
          300: '#95A3A3',
          400: '#697372',
          800: '#0C1717',
          900: '#070011'
        }
      },
```
![Screenshot 2023-10-16 at 11 08 53](https://github.com/tailwarden/komiser/assets/320272/af093a7e-5c55-4ebc-b72e-e5f282959fca)

As you can see the naming scheme differs a bit. It should be unified.

**Additional context**
If you want to tackle this task, feel free to share with us your email address so we can give you access to the Figma project :)

**Comment by Affanzuhaib** [comment]
Can you please assign me this issue

**Comment by umrkhn** [comment]
@Traxmaxx I would like to work on this.
