### ISSUE TITLE
Add avatars as separate components and add them to Storybook

### ISSUE THREAD

**Issue by Traxmaxx** [tailwarden/komiser#1097]
Add avatars as separate components and add them to Storybook. Please check if there are any inline or unshared Avatars in use already and refactor them accordingly

Figma designs can be found [here](https://www.figma.com/file/eq3JgvmW48IVrYcg2kzgLL/Komiser---Design-System?type=design&node-id=1747-13229&mode=dev)

![Screenshot 2023-10-16 at 11 55 52](https://github.com/tailwarden/komiser/assets/320272/4154fb5a-5d9d-45e2-a375-2aafcaef86b8)

**Additional context**
If you want to tackle this task, feel free to share with us your email address so we can give you access to the Figma project :)

**Comment by umrkhn** [comment]
@Traxmaxx I would like to work on this one as well.

**Comment by Traxmaxx** [comment]
@umrkhn all yours! If you provide us your email as @AllieMendes mentioned in #1081 you will receive access to Figma!

Ping me if you need antyhing. I'm also on Discord : )

**Comment by umrkhn** [comment]
I sent her a DM with my email, waiting to be invited.

**Comment by AllieMendes** [comment]
I've invited you to the project and dropped a comment on the Avatars page @umrkhn, thank you for picking this up :)
