### ISSUE TITLE
Fetch single resource by ID

### ISSUE THREAD

**Issue by Traxmaxx** [tailwarden/komiser#1136]
**Is your feature request related to a problem? Please describe.**
There is no way atm to fetch a single resource via API. This would be useful for #1082 and #1072

**Describe the solution you'd like**
Implement a new API endpoint to fetch a single resource by ID

**Describe alternatives you've considered**
None

**Additional context**
See discussion and designs in #1082 and #1072

**Comment by shavidze** [comment]
@Traxmaxx Let me assign it, I'll take this if it's not urgent because I have a virus.

**Comment by Traxmaxx** [comment]
No rush. Hope its nothing serious and you feel better soon 🤞

**Comment by shavidze** [comment]
[__Related PL__](https://github.com/tailwarden/komiser/pull/1139)
