### ISSUE TITLE
Leave feedback modal exceeds screen height

### ISSUE THREAD

**Issue by AllieMendes** [tailwarden/komiser#1166]
**Describe the bug**
The modal for leaving feedback is too long and can exceed the window height, not allowing users to send their feedback or cancel the interaction through the button.

**To Reproduce**
1. I clicked on "Leave Feedback".
2. A modal opened and I couldn't see it all since it continued beyond my window height, with no way to scroll through it.

**Expected behavior**
I'd like to hear your thoughts!
Ideally, we want to have this more as a dropdown component on the page, which can be seen as we scroll through the page, but for now, it would be great to have a workaround.

**Screenshots**
![image](https://github.com/tailwarden/komiser/assets/125025039/32b71b3a-b1ed-4cfc-bc0f-a69ac35309dd)

**Desktop**
 - OS: iOS
 - Browser: Chrome
 - Version: 119

**Comment by gokuljs** [comment]
@mlabouardy can you please assign me this .

**Comment by Azanul** [comment]
There you go @gokuljs! Do drop in to our Discord server in case you have any questions or need help

**Comment by AllieMendes** [comment]
Before tackling this, it would be great to discuss the solution, so I can support with the designs @gokuljs!

**Comment by gokuljs** [comment]
"I'm using a 16-inch Mac, and it works well. However, the issue arises when working with smaller screens. Here are a couple of workarounds I've thought of:

1: The best workaround, in my opinion, is to write the code in such a way that the modal takes up 80% of the screen's height. 
    This approach will make it look normal on larger screens, but on smaller screens, the entire modal will have an 80% height, 
    and it will become scrollable.

2:  Another method I've considered is to shrink the height of the text area and make it scrollable. However, I don't think this is 
     a good idea because there is important content inside that users need to see."

**Comment by gokuljs** [comment]
if this workaround is good then i will create a pr for this @AllieMendes

**Comment by AllieMendes** [comment]
Thank you for the suggestions @gokuljs!
Having the whole modal scrollable is not the best experience as the user loses context of the action.

I explored this in my designs — having a static part for context on the modal and a scrollable part for the content and actions.
![image](https://github.com/tailwarden/komiser/assets/125025039/683da6a0-d83d-4b96-b38d-3c23b0dd5ac2)

Would it be too difficult to implement?

**Comment by gokuljs** [comment]
basically you only want subsection to be scrollable right ?. the header and subtext should always be at the top

**Comment by AllieMendes** [comment]
> basically you only want subsection to be scrollable right ?. the header and subtext should always be at the top

Yes, exactly (with a stroke in the middle to create the separation)

**Comment by gokuljs** [comment]
<img width="691" alt="image" src="https://github.com/tailwarden/komiser/assets/51263906/d4b3a18a-5e51-4e02-af88-73491748b645">
i see one more issue there is no cross icon at the top

**Comment by gokuljs** [comment]
if you have the exisiting figma file for this please share that would be really helpfull.

**Comment by AllieMendes** [comment]
We don't have a component on the Design System for the modal (the original design didn't use a modal at all) but I can invite you to Figma to see this screen exploration in particular — I would need your email for that

**Comment by gokuljs** [comment]
jsgokul123@gmail.com

**Comment by gokuljs** [comment]
<img width="744" alt="image" src="https://github.com/tailwarden/komiser/assets/51263906/9bd28ad2-9d95-4584-87f1-95047ae320ff">
does this look good @AllieMendes

**Comment by gokuljs** [comment]
<img width="1720" alt="image" src="https://github.com/tailwarden/komiser/assets/51263906/3177ba2c-d63e-4099-9fb2-3b1d873f6912">

does this look good @AllieMendes

**Comment by AllieMendes** [comment]
It's getting there!
The top margin should be the same for the scrollbar and the input field.
There should be a bigger margin between the scrollbar and the containers.

I've invited you to Figma, this design is isolated on the page Feedback Collection.

**Comment by gokuljs** [comment]
@AllieMendes this should be perfect right 
<img width="751" alt="image" src="https://github.com/tailwarden/komiser/assets/51263906/5487b142-b236-420b-92a9-2b53fd95ecf3">
