### ISSUE TITLE
Support AWS CodeBuild 

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#1174]
**Describe the solution you'd like**
Collect AWS CodeBuild
Additional context
To get an idea of how to implement the collector, take the [EC2 instances](https://github.com/tailwarden/komiser/blob/master/providers/aws/ec2/instances.go) resource as inspiration.

> Note: only support the AWS resource, please don't add any cost calculation logic

**Comment by AmalRichwin** [comment]
Please assign me this

**Comment by Azanul** [comment]
> Please assign me this

There you go! Do drop by our Discord server if you have any questions or need help
