### ISSUE TITLE
Support AWS CodeCommitt

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#1175]
**Describe the solution you'd like**
Collect AWS CodeCommitt resources
Additional context
To get an idea of how to implement the collector, take the [EC2 instances](https://github.com/tailwarden/komiser/blob/master/providers/aws/ec2/instances.go) resource as inspiration.

> Note: only support the AWS resource, please don't add any cost calculation logic

**Comment by AmalRichwin** [comment]
Hey @jakepage91 I would like to work on this.

**Comment by jakepage91** [comment]
All yours @AmalRichwin
