### ISSUE TITLE
Resource fetching Performance improvement for MongoDB

### ISSUE THREAD

**Issue by Azanul** [tailwarden/komiser#1206]
## Problem
Synchronous fetching of resources for MongoDB

## Describe the solution you'd like
- Update respective function signature
- Use `providers.WorkerPool.SubmitTask` to submit the task to worker pool

## Additional context
Ref PR: https://github.com/tailwarden/komiser/pull/1197

**Comment by tanbirali** [comment]
Please assign this to me?

**Comment by Azanul** [comment]
There you go @tanbirali , feel free to reach oout in case you need help

**Comment by Azanul** [comment]
https://github.com/tailwarden/komiser/pull/1207
