### ISSUE TITLE
Extend AWS support

### ISSUE THREAD

**Issue by Azanul** [tailwarden/komiser#1249]
**Is your feature request related to a problem? Please describe.**
These AWS Services aren't currently supported:
- [x] Certificate Manager
- [x] Cloudformation
- [x] Cloudtrail
- [x] EBS
- [x] EIP
- [x] Glue
- [x] Athena
- [x] MQ Broker
- [x] Lightsail
- [x] Neptune
- [x] Route 53
- [x] Secret Manager
- [x] Data transfer
- [x] EC2 Transit Gateway peering attachment
- [x] EC2 transit Gateway VPC attachment
- [x] Kinesis Firehose delivery stream
- [x] Kinesis Analytics Application
- [x] MSK Cluster
- [x] Nat Gateway
- [x] SNS topic subscription
- [x] WAF 

**Describe the solution you'd like**
- Implement fetching for these particular resources, currently without cost calculations.
- Next step would be adding their support in RDG, contributor may consider implementing it in the same PR.
**Additional context**
Avoiding cost calculations because there's an active effort going on to integrate AWS cost explorer API.

**Comment by Azanul** [comment]
@jakepage91 @AvineshTripathi Feel free to take any of them up. Also, please add any services that you think should be supported and are not listed.

**Comment by jakepage91** [comment]
Added some services
