### ISSUE TITLE
Unexpected Error in Komier Docs

### ISSUE THREAD

**Issue by ManishBisht777** [tailwarden/komiser#1251]
**Describe the bug**
`(https://docs.komiser.io/configuration/cloud-providers/aws)` throwing an unexpected error while loading the page 

**To Reproduce**
1. go to `https://docs.komiser.io`
2. Inside configuration -> cloud-providers -> aws

**Expected behavior**
It should load the page

**Screenshots**
![image](https://github.com/tailwarden/komiser/assets/89926834/ed8b297c-dd0d-46cf-ae82-d2960029ecad)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome, Firefox

**Comment by Azanul** [comment]
Seems like it fixed itself

**Comment by Azanul** [comment]
This is happening again

**Comment by Azanul** [comment]
Might be relevant: https://github.com/mintlify/docs/issues/109

**Comment by Azanul** [comment]
Fixed by https://github.com/tailwarden/komiser/pull/1284
