### ISSUE TITLE
Integrate AWS costexplorer API

### ISSUE THREAD

**Issue by Azanul** [tailwarden/komiser#1255]
**Is your feature request related to a problem? Please describe.**
These AWS Services are pending the interation:
- [X] EC2
- [X] IAM
- [X] SQS
- [X] S3
- [X] EKS
- [X] ECS
- [X] Cloudfront
- [X] RDS
- [X] DynamoDB
- [X] ECR
- [X] SNS
- [X] KMS
- [X] ELB
- [X] CloudWatch
- [X] EFS
- [X] API Gateway
- [X] Elastic Cache
- [X] Service Catalog
- [X] Opensearch
- [X] System Manager
- [X] Kinesis
- [X] Redshift
- [X] CodeBuild
- [X] CodeDeploy

**Describe the solution you'd like**
Filter out the correct resource and add to metdata field
ref PR implementing the same for AWS Lambda: https://github.com/tailwarden/komiser/pull/1247

**Additional context**
Do not ask for assignment, simply put in a PR resolving any subset of the issues. To avoid conflict with any simultaneous implementations, check the comments and comment on this issue before starting.

**Comment by tanbirali** [comment]
I am working on the following cloudfront, ec2, ecs, eks, elasticache, iam, redshift, s3, sqs
