### ISSUE TITLE
Add shortcut to Tailwarden in inventory table

### ISSUE THREAD

**Issue by Azanul** [tailwarden/komiser#1269]
**Is your feature request related to a problem? Please describe.**
Path to the more detailed and precise cost calculations through Tailwarden is not apparent in Komiser.

**Describe the solution you'd like**
- Introduce a new cost status `unknown`.
- Add shortcut to Tailwarden in inventory table according to respective design. 
- Add a warning to overall cost card.

**Design preview**
![Screenshot 2023-12-07 at 3 10 06 PM](https://github.com/tailwarden/komiser/assets/42029519/c32a103f-85ea-47b5-9719-b19ed535d665)
![Screenshot 2023-12-07 at 9 31 07 PM](https://github.com/tailwarden/komiser/assets/42029519/87e85486-516a-496f-a5ac-bc9e3eac708e)

**Additional context**
Reach out to me or @AllieMendes here or over Discord with your email so we can give you access to respective figma designs

**Comment by syedbarimanjan** [comment]
@Azanul @AllieMendes  I would like to work on this. syedbarimanjan@gmail.com

**Comment by syedbarimanjan** [comment]
@Azanul @AllieMendes  can you guide me from where to start?

**Comment by Azanul** [comment]
> syedbarimanjan@gmail.com

I've shared the design with you. Check out the respective design and follow the contributing guide to setup your dev environment.

**Comment by syedbarimanjan** [comment]
> > [syedbarimanjan@gmail.com](mailto:syedbarimanjan@gmail.com)
> 
> I've shared the design with you. Check out the respective design and follow the contributing guide to setup your dev environment.

Thanks I will start work right away.

**Comment by syedbarimanjan** [comment]
> > [syedbarimanjan@gmail.com](mailto:syedbarimanjan@gmail.com)
> 
> I've shared the design with you. Check out the respective design and follow the contributing guide to setup your dev environment.

Thanks I will start work right away.

**Comment by syedbarimanjan** [comment]
@Azanul when I show the unknown status only then do I have to change the Cost to Discoverd Cost?

**Comment by Azanul** [comment]
> @Azanul when I show the unknown status only then do I have to change the Cost to Discoverd Cost?

Where is this "Discovered Cost"?

**Comment by syedbarimanjan** [comment]
@Azanul at the moment you can see Cost on the third card at the top in the design it says to change it for transparency.
![Screenshot 2023-12-28 170824](https://github.com/tailwarden/komiser/assets/112156147/a8e45e44-d657-4302-9aac-36a69592ea71)

**Comment by Azanul** [comment]
> @Azanul when I show the unknown status only then do I have to change the Cost to Discoverd Cost?

Always "Discovered Cost"

**Comment by syedbarimanjan** [comment]
Close this
