### ISSUE TITLE
Add new group-by option in cost explorer

### ISSUE THREAD

**Issue by Azanul** [tailwarden/komiser#1272]
**Is your feature request related to a problem? Please describe.**
Unable to group cost insights by resource

**Describe the solution you'd like**
- Add new group-by option in cost explorer on dashboard according to respective design.
- Add new state to the cost explorer widget

**Design preview**
![Screenshot 2023-12-07 at 7 16 14 PM](https://github.com/tailwarden/komiser/assets/42029519/91492405-4c49-415e-8e07-ec867100fe6c)
![Screenshot 2023-12-07 at 9 36 15 PM](https://github.com/tailwarden/komiser/assets/42029519/fc0c4e4d-bfb9-491d-8fef-261c40d775ec)

**Additional context**
Reach out to me or @AllieMendes here or over Discord with your email so we can give you access to respective figma designs

**Comment by syedbarimanjan** [comment]
@Azanul @AllieMendes  I would like to work on these frontend issues if you will send me the figma designs. syedbarimanjan@gmail.com

**Comment by Azanul** [comment]
> @Azanul @AllieMendes I would like to work on these frontend issues if you will send me the figma designs. [syedbarimanjan@gmail.com](mailto:syedbarimanjan@gmail.com)

I see that you already have an issue assigned to you. Feel free to reach out again once you're done working on that one.

**Comment by syedbarimanjan** [comment]
> > @Azanul @AllieMendes I would like to work on these frontend issues if you will send me the figma designs. [syedbarimanjan@gmail.com](mailto:syedbarimanjan@gmail.com)
> 
> I see that you already have an issue assigned to you. Feel free to reach out again once you're done working on that one.

hey I completed that assigned issue and as I am waiting for a review can I work on this

**Comment by Azanul** [comment]
@syedbarimanjan Go right ahead!

**Comment by syedbarimanjan** [comment]
@Azanul so what I have to do is that I have to create a new groupby option, and upon selecting it I have to show that "Cost at resource level not yet supported" banner.

**Comment by Azanul** [comment]
> @Azanul so what I have to do is that I have to create a new groupby option, and upon selecting it I have to show that "Cost at resource level not yet supported" banner.

Spot on!

**Comment by syedbarimanjan** [comment]
@Azanul close this as it has been completed
