### ISSUE TITLE
Modal underlying overlay has full opacity

### ISSUE THREAD

**Issue by AllieMendes** [tailwarden/komiser#1279]
**Describe the bug**
When a modal or side panel opens, the darker overlay has full opacity, which goes against previous implementations and designs.

**To Reproduce**
1. I clicked on the 'Leave feedback' button.
2. The modal opened, with a backdrop that obscures the rest of the page.

**Expected behavior**
There should be an overlay on top of the underlying layout, but it should have lower opacity as it did in previous releases and as it's documented on the designs.

**Screenshots**
<img width="1493" alt="image" src="https://github.com/tailwarden/komiser/assets/125025039/4746344f-ab1c-415d-893c-739ef07a0ca6">

**Desktop**
OS: iOS
Browser: Chrome
Version: 119

**Additional context**
The link where the bug happened: /inventory

Once assigned, please reach out to me so I can invite you to the Figma file and tag you on the design to use as a reference.

**Comment by ManishBisht777** [comment]
i would like to work on this issue

**Comment by Azanul** [comment]
> i would like to work on this issue

There you go @ManishBisht777
