### ISSUE TITLE
When I run command I got "Error: migrate: migrations table is already locked (constraint failed: UNIQUE constraint failed: bun_migration_locks.table_name (2067))"

### ISSUE THREAD

**Issue by BeamNawapat** [tailwarden/komiser#1281]
**Describe the bug**

When I run command ./komiser start
I got Error: migrate: migrations table is already locked (constraint failed: UNIQUE constraint failed: bun_migration_locks.table_name (2067))

**Comment by Azanul** [comment]
Please add komiser version and steps to reproduce

**Comment by Azanul** [comment]
Stale
