### ISSUE TITLE
Update gray color shades

### ISSUE THREAD

**Issue by AllieMendes** [tailwarden/komiser#1294]
**Feature description**
As we've updated some colors on the designs, we need to update them on the Tailwind config file. 
The shades that need updating are the gray ones.

<img width="837" alt="image" src="https://github.com/tailwarden/komiser/assets/125025039/27d8e74c-d40a-4c5a-a1a4-89b8618d2e73">

**Additional context**
If you want to tackle this task, feel free to share with us your email address so we can give you access to the Figma project :)

**Comment by rstfari** [comment]
I would love to take on this task! christopher.tafari@gmail.com

**Comment by syedbarimanjan** [comment]
syedbarimanjan@gmail.com

**Comment by AllieMendes** [comment]
Thank you both for stepping up!
I'll assign it to @rstfari since they asked first and @syedbarimanjan already has other issues to work on currently
I've invited you to the Figma file, let me know if you have any questions :)

**Comment by rstfari** [comment]
Thank you! I will get started right away!

**Comment by rstfari** [comment]
It looks like the colors are already updated

**Comment by Azanul** [comment]
> It looks like the colors are already updated

Yes, the PR wasn't linked. Here it is: https://github.com/tailwarden/komiser/pull/1295
