### ISSUE TITLE
Pricing bug in AWS Cloudwatch and hardcoded zero cost in some of the aws products

### ISSUE THREAD

**Issue by srikar-jilugu** [tailwarden/komiser#1298]
**Describe the bug**

Inaccurate Cost information for various aws products:

 I was testing komiser on an aws account by setting it up in an ec2-instance using komiser cli  and attached the necessary polices provided in `policy.json` to the corresponding iam role.

* Inaccurate Cloudwatch cost:
<img width="875" alt="Screenshot 2023-12-26 at 7 09 42 PM" src="https://github.com/tailwarden/komiser/assets/139106260/a2114eb4-14ad-43ef-8bc8-be17ccf1bf77">

this is a cloudwatch alarm and its cost is reported as `219$` per month, but as per [cloudwatch pricing](https://aws.amazon.com/cloudwatch/pricing/#:~:text=High%20Resolution%20Metrics,per%20alarm%20metric) it should be only `0.3$ per month`, seems like the cost calculation considers this pricing plan as "per hour" as it calculates here in the code(`0.3*730=219$)`

<img width="700" alt="Screenshot 2023-12-26 at 7 18 52 PM" src="https://github.com/tailwarden/komiser/assets/139106260/94e592cf-58d5-4cf7-88fb-f26f434b5940">

* Hardcoded cost as `0` for RDS, ECS and some other products:
 I can see the cost is returned as 0 in some of the products, it seems like cost computation is not yet integrated for these products but including these products in the inventory is giving false information to the overall cost breakup.
<img width="694" alt="Screenshot 2023-12-26 at 5 28 31 PM" src="https://github.com/tailwarden/komiser/assets/139106260/5d29d57e-4824-474a-a7b3-bc4faf4abd8a">

**To Reproduce**
1. Installed komiser cli on ec2-instance (also tried with docker compose using the image `tailwarden/komiser:3.1.6`
2. created `config.toml` file to get aws account credentials from `ENVIRONMENT_VARIABLES`

**Expected behavior**
* Cost Breakup of the account being inaccurate when compared to **Aws Cost Explorer**

**Screenshots**
If applicable, add screenshots or Loom video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: MacOS 13.5
 - Browser: Chrome
 - Version: latest

Very Impressed by this project btw!

**Comment by AvineshTripathi** [comment]
Hey @srikar-jilugu thanks for notifying us will fix this soon in coming releases.

**Comment by Azanul** [comment]
Hi @bishal7679, is there an update on this?

**Comment by Azanul** [comment]
Closing this issue for the following reasons:
- Cloudwatch bug has been fixed, we now use pricing output to calculate cost.
- Hardcoded costs are hardcoded as 0 because each resource under every service doesn't have a cost associated with it.

Feel free to reopen if you notice otherwise.
