### ISSUE TITLE
At least some cost management abilities for the free version

### ISSUE THREAD

**Issue by hakan-77** [tailwarden/komiser#1340]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
At least some cost management abilities for the free version

**Describe alternatives you've considered**
Another tool

**Additional context**
I started using Komiser, and am quite disappointed to see almost all cost management features require the paid version. 

If you cannot provide this, please at least update the homepage to reflect the reality.

**Comment by mlabouardy** [comment]
Thanks @hakan-77 for the feedback :)

The current version of Komiser indeed offers limited access to certain cost management functionalities. This decision was made carefully, considering the significant investment required to maintain and ensure the accuracy of cost data across multiple cloud providers. Providing detailed and accurate cost insights involves complex integrations and constant updates to keep pace with the ever-changing cloud pricing models and services.

However, we want to assure you that enhancing our cost management features is on our public roadmap and we're looking for contributors and support from the community.

**Comment by hakan-77** [comment]
@mlabouardy understood. I hope you include cost control features in the public version, and also consider updating the home page (readme) so it reflects the current decision. I only installed komiser for the cost element, and then found out I have to use tailwarden service instead.
