### ISSUE TITLE
Can you add a contact email form to your website, as i would like talk or see a demo of the commercial product, 

### ISSUE THREAD

**Issue by DoctorOgg** [tailwarden/komiser#1471]
There is no contact us info on your mail website, and i would like to see about a demo access to try before we commit to the product...  

As i assume the Request Access form is for commiting to buying the product.

**Comment by mlabouardy** [comment]
Hey @DoctorOgg there's no commitment to buy the product with the request access form. You can also contact me at mohamed@tailwarden.com, happy to showcase the product :)
