### ISSUE TITLE
OVHcloud integration won't work

### ISSUE THREAD

**Issue by pascalinthecloud** [tailwarden/komiser#1490]
**Describe the bug**
I tried setting up the ovhcloud integration, but it didn't work. While starting I get the error "2024/08/16 14:17:16 [test][OVH] OVHcloud API error (status code 400): Client::BadRequest: "Invalid signature" (X-OVH-Query-Id:"

**To Reproduce**
1. Try to configure a ovh cloud account

**Expected behavior**
OVHcloud Account should be integrated

**Screenshots**
![image](https://github.com/user-attachments/assets/459b1b67-5713-4d69-8009-9046ab6fa3f2)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave
 - Version 1.67.116
 
 Config.toml looks like this
 
 [[ovh]]
  name="ovh-account"
  endpoint="ovh-eu"
  application_key="my_app_key"
  application_secret="my_application_secret"
  my_consumer_key="my_consumer_key"

[sqlite]
  file="komiser.db

**Comment by pascalinthecloud** [comment]
I've just looked into the source code and found out hat the variable should be "consumer_key" instead of "my_consumer_key".
Maybe you can fix on your documentation (https://docs.komiser.io/configuration/cloud-providers/ovh)

**Comment by AvineshTripathi** [comment]
Hey @pascalinthecloud thanks for reporting this, will fix this asap. Let us know if you need any help!
