### ISSUE TITLE
Support Amazon EFS

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#248]
**Describe the solution you'd like**
Collect AWS EFS

**Additional context**
To get an idea how to implement the collector, take the [S3](https://github.com/tailwarden/komiser/blob/v3.0.0-beta/providers/aws/s3/buckets.go) resource as inspiration.

**Comment by mlabouardy** [comment]
added here https://github.com/tailwarden/komiser/commit/a38a4eab430f05ddccebbf65dcdfdd9d526b0674
