### ISSUE TITLE
Support DigitalOcean Volumes Block Storage

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#257]
**Describe the solution you'd like**
Collect DigitalOcean Volumes Block Storage

**Additional context**
To get an idea of how to implement the collector, take the [Droplet](https://github.com/tailwarden/komiser/blob/v3.0.0/providers/digitalocean/droplets/droplets.go) resource as inspiration.

**Comment by imrishabh18** [comment]
Hey @jakepage91, the URL as linked source for inspiration is not available it seems. It gives a `404` error.

**Comment by mlabouardy** [comment]
Hey @imrishabh18 thanks for reporting the issue
Here's the [link](https://github.com/tailwarden/komiser/blob/v3.0.0/providers/digitalocean/droplets/droplets.go)

**Comment by jakepage91** [comment]
Thanks for that @imrishabh18 all other broken links have been updated!

**Comment by mlabouardy** [comment]
@imrishabh18 let me know if you need a hand on adding the DO block stage resource :)
