### ISSUE TITLE
custom views get deleted whenever pod restarts.

### ISSUE THREAD

**Issue by swamyms123** [tailwarden/komiser#269]
**Describe the bug**
when we create multiple custom views in komiser v3.0.0 it will come under the home page and when the komiser pod restarts and are new pod gets created all the existing custom view gets deleted. we need to create them again to view them.

**To Reproduce**
1. create custom views
2. restart komiser pod

**Expected behavior**
if the pod restart/recreate do not delete custom views.

**Screenshots**
If applicable, add screenshots or Loom video to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please, add here more information about the context of the bug. For example:
Images and/or videos showing the bug:

- The link where the bug happened.
- The cloud provider you were interacting with.
- The email of the account you were using.
- The browser/device you were using.

**Comment by jakepage91** [comment]
Hey there @swamyms123 I'm just going to close this issue since in our chat you told me that the issue was resolved utilizing a PVC to link the postgres db pod inside the PV to the Komiser pod. We are now working on the other issues you shared with us. Thanks.
