### ISSUE TITLE
Filter resources by cost

### ISSUE THREAD

**Issue by neerajjose** [tailwarden/komiser#274]
**Is your feature request related to a problem? Please describe.**
Would need to create custom views of resources that is costing more than a certain amount.

**Describe the solution you'd like**
The `Filter by` drop-down should contain an entry 
- Cost
 
The `operator` section for `Cost` should contain
- Greater Than 
- Between
- Less Than

These would be the Value inputs for each operator
#### Greater Than
- Cost in Dollars
#### Between
- Min Cost in Dollars
- Max Cost in Dollars
### Less Than
- Cost in Dollars

> Only integer values should be accepted

**Comment by mlabouardy** [comment]
Hey @neerajjose thanks a lot for the feature request!
We're working on it and it should be released by the end of this week, meanwhile, you can join our Discord community so you stay up to date with the feature progress :)

**Comment by mlabouardy** [comment]
Hey @neerajjose we've shipped this feature in the latest release https://github.com/tailwarden/komiser/pull/286
Would appreciate your feedback after testing it out 🙏🏻
