### ISSUE TITLE
Civo Provider- multiple bugs 

### ISSUE THREAD

**Issue by saiyam1814** [tailwarden/komiser#275]
1- Docs missing, I tried different tokens as environment variables like `CIVO_TOKEN` and `CIVO_ACCESS_TOKEN` but none of them worked 

My config.toml file 
```
[[civo]]
name="demo"
source="ENVIRONMENT_VARIABLES"
[sqlite]
file="komiser.db"
```

```
 komiser start --port 3000 --config config.toml 
INFO[2023-01-15T06:02:08Z] Debug logging is enabled                     
2023/01/15 06:02:08 NoAPIKeySuppliedError: no API Key supplied, this is required
```

2 - The region for Civo does not appear in the dashboard 
<img width="1378" alt="Screenshot 2023-01-15 at 11 32 35 AM" src="https://user-images.githubusercontent.com/8190114/212525429-237d9d4b-468a-4534-9c8c-0f01c8708caf.png">

3 - There are 4 regions shown, but there are only 3 regions - LON1, FRA1, NYC1
<img width="414" alt="Screenshot 2023-01-15 at 11 32 52 AM" src="https://user-images.githubusercontent.com/8190114/212525444-1eebf54a-9b22-470f-beaf-31e8508af0aa.png">

4 - The cost is zero
<img width="278" alt="Screenshot 2023-01-15 at 11 33 05 AM" src="https://user-images.githubusercontent.com/8190114/212525457-c9deeb9d-3749-45ed-a7ff-8f501f90d090.png">

5 - Civo logo does not appear 
<img width="188" alt="Screenshot 2023-01-15 at 11 33 34 AM" src="https://user-images.githubusercontent.com/8190114/212525471-cb0f3898-d654-47fc-95f9-71a6b8fc3a92.png">

Confi.tom that worked for me after looking at the code 

```
[[civo]]
name="demo"
token="mycivoapikeygoeshere"
[sqlite]
file="komiser.db"
```

**Comment by mlabouardy** [comment]
Hey @saiyam1814 thanks reporting those issues. They were fixed in the latest release (https://github.com/tailwarden/komiser/commit/a912f27461222169ec4d959715d93a7075d8555c)

We're going to update the documentation (https://docs.komiser.io/) to include a section on how to integrate CIVO as well support authentication through environment variables :)

**Comment by saiyam1814** [comment]
What is the environment variable it will take ? When is the next release? Should I build manually ?

**Comment by mlabouardy** [comment]
@saiyam1814 you can just re-download the binary or re-pull the Docker image (the fixes are available in the 3.0.0 version).
As for now, the authentication works by referencing the token in the config.toml (we'll support passing the token as `CIVO_TOKEN` environment variables later on this week)
```
[[civo]]
name="demo"
token="mycivoapikeygoeshere"
[sqlite]
file="komiser.db"
```

**Comment by saiyam1814** [comment]
@mlabouardy thanks,  So I just checked, and there are some costs still with $0 which might be wrong, also is there a way to add multiple providers with the same komiser ? 
<img width="1465" alt="Screenshot 2023-01-17 at 5 49 28 PM" src="https://user-images.githubusercontent.com/8190114/212897369-171e59aa-9914-447c-88d1-59adf5bee28a.png">

**Comment by saiyam1814** [comment]
Excellent, there is a cloud cost optimization webinar tomorrow, I will try to show Komiser if everything gets in https://www.civo.com/meetups/cost-of-cloud

**Comment by mlabouardy** [comment]
thanks a million @saiyam1814, just pushed the right cost formula for compute instances as well the cost for k8s service (you can try it out once the [build](https://app.circleci.com/pipelines/github/tailwarden/komiser/347/workflows/e6b0df27-23f8-453d-8de0-8ab0ba7ca2de) is over)

**Comment by saiyam1814** [comment]
Cool, Thanks, try to attend if you can :)

**Comment by mlabouardy** [comment]
FYI, we've release a video on how to integrate CIVO to Komiser:
https://www.youtube.com/watch?v=NBbEpoW-kVs

**Comment by saiyam1814** [comment]
Nice, I will be giving you a shoutout in todays webinar in 2 hours
