### ISSUE TITLE
Filter on Specific Tag doesn't parse ":"

### ISSUE THREAD

**Issue by leccles1** [tailwarden/komiser#280]
**Describe the bug**
When attempting to filter specific tags that contain a colon (:) it results in the following error in the front-end

I believe this is down to the way filter parameters are used by Komiser, as the URL uses colon separators between filter types, operators and values.

```
Filter could not be applied!

Please refresh the page and try again.
```

localhost:3000/?tag:sst:app:CONTAINS:test <-- Fails

http://localhost:3000/?tag:sst-app:CONTAINS:test <-- Succeeds, when colon swapped for dash (-)

**To Reproduce**
1. Select Filter
2. Select by specific tag
3. Enter any tag name that contains a colon ":"
4. Enter any condition criteria (is, contains, etc)
5. Click apply filter

**Expected behavior**
Komiser filter params are handled to correctly escape all characters, I attempted to manually escape the colon using "\:" and encoding the value myself "sst%3Aapp" however it still resulted in error

**Screenshots**
If applicable, add screenshots or Loom video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS M1
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 108.0.5359.124

**Additional context**
I'm using an IaC framework to provision AWS resources, so cannot modify the tag name in use, it defaults deployed resources to contain tags such as "sst:app" to denote the application name the resource belongs to.

**Comment by mlabouardy** [comment]
Thanks @leccles1 I'll push a fix in a few

**Comment by mlabouardy** [comment]
Hey @leccles1 we've pushed a quick fix in the latest release, let me know if its works fine

**Comment by leccles1** [comment]
Hey @mlabouardy, wow that turn around, great work! 

I'm using Komiser via docker image whilst testing /playing around with it, I've just destroyed, deleted images and re-ran the container but I don't think the image is pulling the latest release code / could be looking at the 3.0.0 tag?

**Comment by mlabouardy** [comment]
Hey @leccles1, yes its 3.0.0 tag.
I think the [CI](https://app.circleci.com/pipelines/github/tailwarden/komiser/366/workflows/7eb8257f-9746-4be2-9dfc-596786ff6990) was still building the image, you can re-pull the image now :) 
Also, FYI, in the same release, you can now breakdown your resources by cost [see here](https://github.com/tailwarden/komiser/pull/286)

**Comment by leccles1** [comment]
Ah yes, I've pulled and re-built the latest now and am able to filter for my resources using tags containing ":"

One thing I have noticed, saving a view with the tag, the applied filter appears to miss text after the ":"

so for the tag "sst:app" It's showing the filter value as "Specific tag: sst :is:stacked-wallet"

But overall the functionality is working and I am able use filters with a colon without error 🎉

<img width="1260" alt="Screenshot 2023-01-20 at 16 34 21" src="https://user-images.githubusercontent.com/17564257/213753706-30770a10-c171-46b2-8dbe-1b7114c7e7dc.png">

**Comment by mlabouardy** [comment]
Glad to hear that 😄 
It was a quick fix, we'll release a stable patch this weekend :)
