### ISSUE TITLE
Civo Costing 

### ISSUE THREAD

**Issue by saiyam1814** [tailwarden/komiser#285]
So there needs to be change in the pricing as the costs for CPU and RAM optimised nodes are different. 

Let me explain 
for CPU optimized: 
16*8=$128
32*8=$256 and so on  
for Ram optimised 
16*4.5 = 72
32*4.5=144 and so on
For standard and performance its 
Ram GB * 5
I think we can have if conditions based on Standatd || Performance - cost per RAM GB = $5 
second, if CPU optimized 
 cost per RAM GB = $8 
Lastly if RAM optimized 
 cost per RAM GB = $4.5

CPu optimizes 
![image](https://user-images.githubusercontent.com/8190114/213721317-3b85fbe6-9c56-4629-9050-4019869a20dc.png)

Ram optimized
![image](https://user-images.githubusercontent.com/8190114/213721382-b226875d-ed99-4a0d-a6e9-c18b50bb1009.png)

**Comment by mlabouardy** [comment]
thanks @saiyam1814 for the feedback, will work on a fix shortly and ping you when its ready for review

**Comment by mlabouardy** [comment]
@saiyam1814 we've updated the pricing of K8s nodes to take into consideration the node instance type (General purpose, Performance, CPU or Ram optimized) https://github.com/tailwarden/komiser/blob/master/providers/civo/kubernetes/clusters.go#L48

**Comment by saiyam1814** [comment]
Perfect thanks!
