### ISSUE TITLE
Komiser AWS credentials fetching issue 

### ISSUE THREAD

**Issue by Lithesh-Infolob** [tailwarden/komiser#305]
![Screenshot (473)](https://user-images.githubusercontent.com/122088752/215088585-a909a676-0892-409b-892c-d7cb242a868b.png)

**Comment by fpapadamis** [comment]
Hi, I've been using `komiser 3.0.0` with AWS  without any issues.

Example `config.toml`:
```
[[aws]]
name="production"
source="CREDENTIALS_FILE"
path="/etc/config/credentials.yaml"
profile="default"

[sqlite]
file="komiser.db"
```

Example `credentials.yaml`:
```
[default]
aws_access_key_id = xxxxxxxxxxxxxxxx
aws_secret_access_key = xxxxxxxxxxxxxxxxxxxxxxxxxxx
```

Example command:
`komiser start --config /etc/config/config.toml`
