### ISSUE TITLE
Center the Div to align the content

### ISSUE THREAD

**Issue by ShivamTyagi12345** [tailwarden/komiser#314]
**Is your feature request related to a problem? Please describe.**
I like it when the pixels go in a hand in hand fashion, and the UI follows that mostly , except for https://www.komiser.io/

**Describe the solution you'd like**

I would like the content to be within the #5CC7C7 background, and not enter the white region at all

![image](https://user-images.githubusercontent.com/60812924/216134606-debcbc94-6309-49c5-b7ab-0d31a108111b.png)

 
**Describe alternatives you've considered**
Yes I can add this css, to improve the design to
`.community-card-content {
 max-width:25.5rem;
 line-height:2;
 /*! display: flex; *//*! align-content: center; */color: black;
 margin-right: 7rem;
}
`

![image](https://user-images.githubusercontent.com/60812924/216138570-32d0eeab-353a-4522-93d1-35af61c6ace4.png)

**Additional context**
I can fix this issue  for you , if assigned 
( :

**Comment by mlabouardy** [comment]
Thanks a million @ShivamTyagi12345 I'll push the fix (our landing page is hosted on Webflow)
Meanwhile, you can join our [Discord community](https://discord.tailwarden.com), we've few topics that you can contribute to (we'll sponsor your fav open-source project as a token of appreciation 😄)

**Comment by ShubhamPalriwala** [comment]
Let's close this @mlabouardy, as I can see that the component is fixed now?
![Screenshot_2023-06-11-16-28-10_4920x1920](https://github.com/tailwarden/komiser/assets/55556994/7d7ced29-fbe0-4431-a95a-d962ae8f6a13)

**Comment by mlabouardy** [comment]
> Let's close this @mlabouardy, as I can see that the component is fixed now? ![Screenshot_2023-06-11-16-28-10_4920x1920](https://user-images.githubusercontent.com/55556994/244931604-7d7ced29-fbe0-4431-a95a-d962ae8f6a13.png)

Done :)
