### ISSUE TITLE
Support Civo Database

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#316]
Describe the solution you'd like
Collect Civo Database instances

Additional context
To get an idea of how to implement the collector, take the [Civo Intances](https://github.com/tailwarden/komiser/blob/master/providers/civo/compute/instances.go) resource as inspiration.

**Comment by mlabouardy** [comment]
@mahendrabagul done, would you mind joining our Discord (http://discord.tailwarden.com) so I can add you to the contributors channel :)
