### ISSUE TITLE
Support Kubernetes Deployment Objects

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#325]
**Describe the solution you'd like**
Collect Kubernetes Deployment objects

**Additional context**
To get an idea of how to implement the collector, take the [Kubernetes pods](https://github.com/tailwarden/komiser/blob/master/providers/k8s/core/pods.go) resource as inspiration.

**Comment by kranurag7** [comment]
Covered in this issue #321

**Comment by ImranShahShaik** [comment]
@jakepage91 Hi Jake. I Saw This Labeled as Good First Issue. Can you Guide me towards a more easier one so that I may change my contribution score from 0->1

**Comment by mlabouardy** [comment]
Thanks @kranurag7 
@ImranShahShaik here's a hands-on blog post on how to contribute to Komiser https://www.tailwarden.com/blog/how-to-contribute-to-komiser
