### ISSUE TITLE
Use namespaces when provider is Kubernetes

### ISSUE THREAD

**Issue by kranurag7** [tailwarden/komiser#333]
**Is your feature request related to a problem? Please describe.**

As of now, we are using regions when the provider is kubernetes and I think we should use namespaces instead of regions. 

**Describe the solution you'd like**

Instead of using regions, we can use namespaces and for covering cloud provider specific kubernetes offering like GKE, EKS etc. we can cover that in the cloud provider specific implementation only for calculating the associated cost with the cluster workloads at a more granular level. 

**Describe alternatives you've considered**

**Additional context**

**Comment by mlabouardy** [comment]
That's a great idea @kranurag7
would you mind pushing a fix for that?
