### ISSUE TITLE
Integrate with CloudQuery?

### ISSUE THREAD

**Issue by yevgenypats** [tailwarden/komiser#341]
Hey folks!

I'm the founder of [cloudquery](https://github.com/cloudquery/cloudquery) we are an open source high performance ELT framework.

I stumbled across this project and thought it might be interesting to collaborate and help with maintenance  around mutual integrations. We are maintaining [AWS, GCP, Azure, k8s, AliCloud, DigitalOcean, and many others](https://www.cloudquery.io/docs/plugins/sources/overview) plugins which I think you can use and it will save you a lot of work and boost your platform in terms of number of integrations and resources.

We are also looking to create an OVH plugin but we are looking for maintainers (maybe this will be interesting for you to help maintain) and of-course if you can help us with contributions to any other plugins this would be amazing so I think there can be a win win here :)

Will be happy to chat offline as well. Im available `yp` at `cloudquery.io` or on our discord https://cloudquery.io/discord

Thanks!
Yevgeny

**Comment by mlabouardy** [comment]
Hey @yevgenypats
Integrating with CloudQuery would be ideal, I've added the feature to our [public roadmap](https://roadmap.tailwarden.com/feature-requests/p/cloudquery-integration) :)
Would love to give a hand on OVH and other EU cloud providers (such as Scaleway) :) 
I'll shoot you an email and I'm going to join your Discord to discuss how we can take this further!

**Comment by Azanul** [comment]
Integration with cloudquery would require a ton of work. We might get back to it, reopen the issue.
