### ISSUE TITLE
Set maxlength for custom view's name input

### ISSUE THREAD

**Issue by mlabouardy** [tailwarden/komiser#358]
Set a maximum character limit in input field to avoid the following:

![image](https://user-images.githubusercontent.com/10320205/218455882-c0c5d696-7a66-45ed-acb4-ac6d4161d8b9.png)

**Comment by rabira-hierpa** [comment]
@mlabouardy let me work on this one

**Comment by mlabouardy** [comment]
just assigned to you @rabira-hierpa

**Comment by shobhitexe** [comment]
Hello , is this issue still open I would love to work on this

**Comment by shobhitexe** [comment]
> > Hello , is this issue still open I would love to work on this
> 
> you can take it, I've assigned it to you :)


Hey I have a small question regarding the use of the maxLength attribute in input fields. I have noticed that maxLength is not explicitly specified in any input fields, so I am considering adding it to all possible input fields with a limit of 20 characters. I would like to know if I should apply the 20-character limit uniformly to all fields, or if different fields might have different limits. However, based on my testing, a limit of 20 characters seems to be working fine for all fields.

**Comment by mlabouardy** [comment]
> > > Hello , is this issue still open I would love to work on this
> > 
> > 
> > you can take it, I've assigned it to you :)
> 
> Hey I have a small question regarding the use of the maxLength attribute in input fields. I have noticed that maxLength is not explicitly specified in any input fields, so I am considering adding it to all possible input fields with a limit of 20 characters. I would like to know if I should apply the 20-character limit uniformly to all fields, or if different fields might have different limits. However, based on my testing, a limit of 20 characters seems to be working fine for all fields.

Hey @shobhitexe, 20 characters might not be enough (especially for custom view's name and tag/key values), so I would aim for a 64 as a limit for all the input fields :)
