### ISSUE TITLE
Estimate cost of AWS Elasticache resources

### ISSUE THREAD

**Issue by mlabouardy** [tailwarden/komiser#369]
**Describe the solution you'd like**
Estimate cost of AWS ElastiCache resources

**Additional context**
To get an idea of how to estimate cost, take the [EC2](https://github.com/tailwarden/komiser/blob/master/providers/aws/ec2/instances.go) resource as inspiration.

**Comment by RohanMishra315** [comment]
Hey @ShubhamPalriwala @jakepage91 why is this still open?

**Comment by Azanul** [comment]
> Hey @ShubhamPalriwala @jakepage91 why is this still open?

An oversight. Thanks for pointing it out
