### ISSUE TITLE
Support AWS provisioned RDS instances

### ISSUE THREAD

**Issue by fpapadamis** [tailwarden/komiser#371]
**Is your feature request related to a problem? Please describe.**
Currently, `komiser` supports only RDS Aurora and Multi-AZ DB clusters.
As stated in [DescribeDBClusters](https://github.com/aws/aws-sdk-go-v2/blob/main/service/rds/api_op_DescribeDBClusters.go) that is used to fetch the data:
> // Returns information about Amazon Aurora DB clusters and Multi-AZ DB clusters.

**Describe the solution you'd like**
Support for provisioned RDS instances should be implemented.

**Comment by fpapadamis** [comment]
You may assign it to me.

**Comment by mlabouardy** [comment]
ofc, thanks for taking this @fpapadamis
