### ISSUE TITLE
Support Azure Firewall

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#392]
Describe the solution you'd like
Collect Azure Firewall

**Additional context**
To get an idea of how to implement the collector, take the [VM](https://github.com/tailwarden/komiser/blob/master/providers/azure/compute/virtual_machines.go) resource as inspiration.

**Comment by Mayank-032** [comment]
Please assign this issue to me.

**Comment by jakepage91** [comment]
It's your! Thanks @Mayank-032

**Comment by jakepage91** [comment]
Hey there @Mayank-032 I hope you are doing well. I just wanted to check in with you to see if you needed any help with this issue. Have a great day mate. Cheers!
