### ISSUE TITLE
Support Azure Local Network Gateways

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#396]
Describe the solution you'd like
Collect Azure Local Network Gateways

**Additional context**
To get an idea of how to implement the collector, take the [VM](https://github.com/tailwarden/komiser/blob/master/providers/azure/compute/virtual_machines.go) resource as inspiration.

**Comment by azgcloudev** [comment]
I am working in this one @jakepage91

**Comment by azgcloudev** [comment]
Resource created

<img width="1272" alt="image" src="https://github.com/tailwarden/komiser/assets/72358828/57d8b8cc-d182-4087-bdcd-2c677bad537a">

**Comment by azgcloudev** [comment]
@jakepage91  this issue can be closed
