### ISSUE TITLE
Support Azure queues storage

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#403]
Describe the solution you'd like
Collect Azure Queues Storage

**Additional context**
To get an idea of how to implement the collector, take the [VM](https://github.com/tailwarden/komiser/blob/master/providers/azure/compute/virtual_machines.go) resource as inspiration.

**Comment by Kolawole99** [comment]
@jakepage91 assign this issue to me.

**Comment by jakepage91** [comment]
It's yours! @Kolawole99

**Comment by Kolawole99** [comment]
I have opened a PR on this issue [here](https://github.com/tailwarden/komiser/pull/422) @jakepage91
