### ISSUE TITLE
Document Toast component on Storybook

### ISSUE THREAD

**Issue by victorgaard** [tailwarden/komiser#419]
**Describe the solution you'd like**
Document our Toast component on Storybook. 
Component can be found on: `/dashboard/components/toast`

**Additional context**
- The current folder structure we are using for Storybook is to add the mocks and stories in the same folder as the component. Feel free to duplicate the Template from `/dashboard/components/template`
- `npm run storybook` to have Storybook up & running.

**Screenshots**
<img width="719" alt="image" src="https://user-images.githubusercontent.com/13384559/221204643-31b4b445-7d78-44fc-b165-be9da159dee4.png">

**Comment by eneskaya** [comment]
Closed by #443
