### ISSUE TITLE
Make successful provider integrations known

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#435]
**Is your feature request related to a problem? Please describe.**
When you add the authentication credentials to the config.toml file and run Komiser, unless there are resources in your target cloud provider, there is no way to know if the configuration was successful or if there was some issue.

I have the use case in which I don't have any resources (that are currently supported by Komiser) in my Azure account. When I run Komiser I don't know if the integration was successful. I needed to spin up a VM to make sure the integration worked. This is extra work that would be nice to avoid if I could see a message in the logs or if the Komiser dashboard could show the number of `successful integration` under cloud account, instead of only showing the cloud accounts that actually have fetched resources.

**Describe the solution you'd like**
Initially it would be cool to see output in the CLI logs that informs on the status of the integration attempt `Your Azure account has been successfully integrated` for example. 

What might require a bit more work would be to include the cloud provider in the providers filter list even if there are no resources fetched, as long as Komiser can access the cloud provider.

**Comment by AvineshTripathi** [comment]
Hey @jakepage91 do you mean we should log for individual cloud after reading and loading the configs for respective cloud platforms i.e. inside https://github.com/tailwarden/komiser/blob/master/internal/config/load.go#L64?

**Comment by jakepage91** [comment]
Hey there @AvineshTripathi to be honest I don't know exactly where the logic should be placed. But it would be great if we had a way to show if the integration is successful, regardless if the target account has any resources in it or not. I think @mlabouardy might have started working on this one, not sure though.

**Comment by jakepage91** [comment]
For sure! Will do, thanks a million @AvineshTripathi
