### ISSUE TITLE
SHA mismatch when installing with Brew

### ISSUE THREAD

**Issue by somoore** [tailwarden/komiser#442]
**Describe the bug**
When installing with brew:
```
testing@mac-pro ~ % brew install komiser
==> Fetching tailwarden/komiser/komiser
==> Downloading https://cli.komiser.io/3.0.4/osx/amd/komiser
######################################################################## 100.0%
Error: komiser: SHA256 mismatch
Expected: 06a4d7e279fcb0e17563eafa5db708eb516bcf3364722b76ec69d70fe90de1fc
  Actual: 261b3fa911b9abf764f25217c369e89acf34dc42996cdc17270bca9d7bbd9174
    File: /Users/testing/Library/Caches/Homebrew/downloads/64f5ce04a3717ef6a91884ff0720c6ac3e1bbb1236781c11d6d13e94cd1727d3--komiser
To retry an incomplete download, remove the file above.
```

**To reproduce:**
```
brew tap tailwarden/komiser
brew install komiser
```

**Expected behavior:**
Komiser installs

**Environment:**
macOS Monterey (v12.6.3)
brew version 4.0.4

**Additional Context:**
Tried the following:
`brew update`
as well as removing the file from` /Users/testing/Library/Caches/Homebrew/downloads/` , issue with SHA mismatch persists.
![komiser](https://user-images.githubusercontent.com/59924790/222514522-6bbba816-ab3b-4716-8555-983ad7a95b8a.png)

**Comment by jakepage91** [comment]
True! Thanks for pointing this out. I'm on it!

**Comment by jakepage91** [comment]
Should be fixed now! 

Run 
```
brew update
brew install komiser
```

Thanks again @somoore

**Comment by somoore** [comment]
no problem at all, works on my side now! thanks for the quick fix!
