### ISSUE TITLE
Support Amazon CloudWatch metric-stream

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#464]
**Describe the solution you'd like**
Collect Amazon CloudWatch metric-stream
**Additional context**
To get an idea of how to implement the collector, take the [CloudWatch alarms](https://github.com/tailwarden/komiser/blob/master/providers/aws/cloudwatch/alarms.go) resource as inspiration.

**Comment by ShubhamPalriwala** [comment]
Taking this up as well (haha its similar)
