### ISSUE TITLE
Support Amazon CloudWatch log group

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#466]
**Describe the solution you'd like**
Collect Amazon CloudWatch log group
**Additional context**
To get an idea of how to implement the collector, take the [CloudWatch alarms](https://github.com/tailwarden/komiser/blob/master/providers/aws/cloudwatch/alarms.go) resource as inspiration.

**Comment by ShubhamPalriwala** [comment]
Taking this up!

**Comment by mlabouardy** [comment]
> Taking this up!

all yours :)
