### ISSUE TITLE
Support Amazon EC2 key-pair

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#495]
**Describe the solution you'd like**
Collect Amazon EC2 key-pair
**Additional context**
To get an idea of how to implement the collector, take the [EC2 instances](https://github.com/tailwarden/komiser/blob/master/providers/aws/ec2/instances.go) resource as inspiration.

**Comment by ShubhamPalriwala** [comment]
taking this up!

**Comment by mlabouardy** [comment]
> taking this up!

all yours!

**Comment by ShubhamPalriwala** [comment]
@jakepage91 lets close this?
