### ISSUE TITLE
Support Amazon EC2 network-interface

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#502]
**Describe the solution you'd like**
Collect Amazon EC2 network-interface
**Additional context**
To get an idea of how to implement the collector, take the [EC2 instances](https://github.com/tailwarden/komiser/blob/master/providers/aws/ec2/instances.go) resource as inspiration.

**Comment by ShubhamPalriwala** [comment]
this is already implemented hence can be closed? https://github.com/tailwarden/komiser/blob/develop/providers/aws/ec2/network_interfaces.go

**Comment by ShubhamPalriwala** [comment]
@jakepage91 lets close this as well?
