### ISSUE TITLE
Support Amazon EC2 security-group-rule

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#507]
**Describe the solution you'd like**
Collect Amazon EC2 security-group-rule
**Additional context**
To get an idea of how to implement the collector, take the [EC2 instances](https://github.com/tailwarden/komiser/blob/master/providers/aws/ec2/instances.go) resource as inspiration.

**Comment by ShubhamPalriwala** [comment]
we already have this? https://github.com/tailwarden/komiser/blob/a38a4eab430f05ddccebbf65dcdfdd9d526b0674/providers/aws/ec2/security_groups.go

**Comment by ShubhamPalriwala** [comment]
@jakepage91 lets close this as well?
