### ISSUE TITLE
Support Amazon EC2 vpc-peering-connection

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#524]
**Describe the solution you'd like**
Collect Amazon EC2 vpc-peering-connection
**Additional context**
To get an idea of how to implement the collector, take the [EC2 instances](https://github.com/tailwarden/komiser/blob/master/providers/aws/ec2/instances.go) resource as inspiration.

**Comment by mlabouardy** [comment]
> @jakepage91 assign this issue to me

all yours

**Comment by Kolawole99** [comment]
Hey @jakepage91 and @mlabouardy I have opened a PR that adds this feature https://github.com/tailwarden/komiser/pull/770

**Comment by mlabouardy** [comment]
> Hey @jakepage91 and @mlabouardy I have opened a PR that adds this feature #770

merged, thanks a lot
