### ISSUE TITLE
Support Amazon ECS container-instance

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#529]
**Describe the solution you'd like**
Collect Amazon ECS container-instance
**Additional context**
To get an idea of how to implement the collector, take the [ECS clusters](https://github.com/tailwarden/komiser/blob/master/providers/aws/ecs/clusters.go) resource as inspiration.

**Comment by aimanafzal** [comment]
@jakepage91 Please assign this to me. I have already started on it.

**Comment by jakepage91** [comment]
Sure thing, all yours @aimanafzal!

**Comment by aimanafzal** [comment]
Thanks!

On 26-Jun-2023, at 2:39 PM, Jake Page ***@***.***> wrote:



Sure thing, all yours @aimanafzal<https://github.com/aimanafzal>!

**Comment by aimanafzal** [comment]
> Sure thing, all yours @aimanafzal!

PR Created 👍
