### ISSUE TITLE
Support AWS IAM instance-profile

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#542]
**Describe the solution you'd like**
Collect AWS IAM instance-profile
**Additional context**
To get an idea of how to implement the collector, take the [IAM role](https://github.com/tailwarden/komiser/blob/master/providers/aws/iam/roles.go) resource as inspiration.

**Comment by fpapadamis** [comment]
You may assign it to me.

**Comment by jakepage91** [comment]
Yours! Thanks @fpapadamis
