### ISSUE TITLE
Support AWS IAM policy

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#544]
**Describe the solution you'd like**
Collect AWS IAM policy
**Additional context**
To get an idea of how to implement the collector, take the [IAM role](https://github.com/tailwarden/komiser/blob/master/providers/aws/iam/roles.go) resource as inspiration.

**Comment by fpapadamis** [comment]
You may assign it to me.

**Comment by jakepage91** [comment]
Yours! Thanks @fpapadamis

**Comment by fpapadamis** [comment]
Hey @jakepage91, this has been merged.
