### ISSUE TITLE
Support AWS IAM user

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#547]
**Describe the solution you'd like**
Collect AWS IAM user
**Additional context**
To get an idea of how to implement the collector, take the [IAM role](https://github.com/tailwarden/komiser/blob/master/providers/aws/iam/roles.go) resource as inspiration.

**Comment by fpapadamis** [comment]
You may assign it to me.

**Comment by ShubhamPalriwala** [comment]
This issue is again up for grabs, if anybody wants to work on this, please comment below and we would be happy to assign it back to you! :1st_place_medal:

If you had already started working on it and we unassigned you, we apologise for it, just drop a comment and we'd reassign it back!

**Comment by siddarthkay** [comment]
Hey @ShubhamPalriwala and @jakepage91 !
I'd like to pick this one up :) 
Can you please assign this to me?

**Comment by ShubhamPalriwala** [comment]
Sure @siddarthkay :rocket:
