### ISSUE TITLE
Support AWS Lambda event-source-mapping

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#550]
**Describe the solution you'd like**
Collect AWS Lambda event-source-mapping
**Additional context**
To get an idea of how to implement the collector, take the [Lambda function](https://github.com/tailwarden/komiser/blob/master/providers/aws/lambda/functions.go) resource as inspiration.

**Comment by jakepage91** [comment]
Sure thing @GenMech

**Comment by jakepage91** [comment]
I also see you have this one and #578 if you need any help we would love to be of service!

**Comment by GenMech** [comment]
Hey @jakepage91, I was pretty occupied with my college commitments. I will resume working on my issues. Can you tell me some doc or give me some guidance on setting up config file.

**Comment by jakepage91** [comment]
Sure no worries @GenMech. This should help you https://docs.komiser.io/docs/cloud-providers/aws#example-configtoml

**Comment by VedankPande** [comment]
Hey @jakepage91. I'd like to work on this, can you assign it to me?

**Comment by jakepage91** [comment]
All your's @VedankPande and just so you know this issue is Hacktoberfest eligilbe 👍
