### ISSUE TITLE
Amazon OpenSearch Service Domain

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#551]
**Describe the solution you'd like**
Collect Amazon OpenSearch Service Domain
**Additional context**
To get an idea of how to implement the collector, take the [Lambda function](https://github.com/tailwarden/komiser/blob/master/providers/aws/lambda/functions.go) resource as inspiration.

**Comment by ShubhamPalriwala** [comment]
Taking this up as well!

**Comment by mlabouardy** [comment]
all yours!

**Comment by eneskaya** [comment]
Fixed with #727
