### ISSUE TITLE
Support Amazon RDS auto-backup

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#559]
**Describe the solution you'd like**
Collect Amazon RDS auto-backup
**Additional context**
To get an idea of how to implement the collector, take the [RDS instances](https://github.com/tailwarden/komiser/blob/master/providers/aws/rds/instances.go) resource as inspiration.

**Comment by siddarthkay** [comment]
Hi @jakepage91 @mlabouardy : I'd like to take this one up next, Please assign it to me when you get a chance :)

**Comment by ShubhamPalriwala** [comment]
Hey @siddarthkay, any update on this? let me know if you need a hand here and we can get this going! 🤝

**Comment by siddarthkay** [comment]
Hey @ShubhamPalriwala : Thanks for the reminder. 
Sorry I meant to send out a PR last month itself but got caught up in other things. 
I'll rebase and have the PR ready next week.
I really appreciate your offer for helping out on this one, I'll reach out to you if and when I get stuck on something.
