### ISSUE TITLE
Support Amazon RDS db-proxy-endpoint

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#565]
**Describe the solution you'd like**
Collect Amazon RDS db-proxy-endpoint
**Additional context**
To get an idea of how to implement the collector, take the [RDS Instances](https://github.com/tailwarden/komiser/blob/master/providers/aws/rds/instances.go) resource as inspiration.

**Comment by siddarthkay** [comment]
since I already have an RDS instance running, I can try this one as well, please assign this issue to me @jakepage91

**Comment by jakepage91** [comment]
Yours!

**Comment by siddarthkay** [comment]
@jakepage91 and @mlabouardy , is https://github.com/tailwarden/komiser/issues/564 a duplicate? not sure.
