### ISSUE TITLE
Support AWS Service Catalog applications

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#577]
**Describe the solution you'd like**
Collect AWS Service Catalog applications
**Additional context**
To get an idea of how to implement the collector, take the [RDS Instances](https://github.com/tailwarden/komiser/blob/master/providers/aws/rds/instances.go) resource as inspiration.

**Comment by ShubhamPalriwala** [comment]
taking this up!

**Comment by ShubhamPalriwala** [comment]
this can be closed now?

**Comment by ShubhamPalriwala** [comment]
@jakepage91
