### ISSUE TITLE
Support AWS Systems Manager maintenancewindow

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#583]
**Describe the solution you'd like**
Collect AWS Systems Manager maintenancewindow
**Additional context**
To get an idea of how to implement the collector, take the [S3 buckets](https://github.com/tailwarden/komiser/blob/master/providers/aws/s3/buckets.go) resource as inspiration.

**Comment by ShubhamPalriwala** [comment]
taking this up!

**Comment by ShubhamPalriwala** [comment]
@jakepage91 lets close this?
