### ISSUE TITLE
Estimate cost for CIVO firewalls

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#601]
**Describe the solution you'd like**
Estimate cost of CIVO firewalls

**Additional context**
To get an idea of how to estimate cost, take the [CIVO objectstore](https://github.com/tailwarden/komiser/blob/master/providers/civo/storage/objectstores.go) resource as an example

**Comment by ShubhamPalriwala** [comment]
Hey just to make sure I am getting this right, I need something like this as used in objectStore as per the costing rules of firewall right?
```go
		monthlyCost := float64(store.MaxSize/500) * 5
```
[here](https://github.com/tailwarden/komiser/blob/master/providers/civo/network/firewalls.go) right and then pass the same instead of the 0 cost?

**Comment by jakepage91** [comment]
Exactly @ShubhamPalriwala you would need to find out the pricing scheme for CIVO firewalls and then substitute the 0 value for the output of the resulting logic you use to calculate the cost.

**Comment by ShubhamPalriwala** [comment]
Was just going through it and having difficult time finding it out, but found the pricing for databases and that's also in a ToDo so taking that up right now!

**Comment by jakepage91** [comment]
Sounds good! Would you like me to assign it to you?

**Comment by ShubhamPalriwala** [comment]
Update: looks like they have removed the firewall price offering from their docs and the website, have reached out to their support team to see if I can get anythin

**Comment by ShubhamPalriwala** [comment]
Hey @jakepage91, just got a word from their support team:
![Screenshot_2023-04-04-17-53-42_3000x1920](https://user-images.githubusercontent.com/55556994/229790533-5014008c-291b-4eba-8e42-b952aa7a9d2c.png)

Looks like we already did the highly complex cost calculation haha
