### ISSUE TITLE
Estimate cost of OCI BlockVolumes

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#608]
Describe the solution you'd like
Estimate cost of OCI [BlockVolumes](https://github.com/tailwarden/komiser/blob/master/providers/oci/storage/blockvolumes.go)

Additional context
No cost calculation has been added to any of the OCI resources but in this case perhaps something similar to this can be implemented.

```
        // calculate cost
        volumeRequest := core.GetVolumeRequest{
            VolumeId: volume.Id,
        }
        volumeResponse, err := blockStorageClient.GetVolume(context.Background(), volumeRequest)
        if err != nil {
            return resources, err
        }
        cost := *volumeResponse.Volume.SizeInGBs * *volumeResponse.Volume.PerGBMonth
```

**Comment by Freedisch** [comment]
hello @jakepage91, I would like to work on this issue

**Comment by jakepage91** [comment]
Sure thing @Freedisch!
