### ISSUE TITLE
Support MongoDB Atlas Serverless clusters

### ISSUE THREAD

**Issue by eneskaya** [tailwarden/komiser#618]
**Describe the solution you'd like**

Collect all clusters, including serverless clusters

**Additional context**
To get an idea of how to implement the collector, take the [MongoDB Clusters](https://github.com/tailwarden/komiser/blob/master/providers/mongodbatlas/clusters/clusters.go) resource as inspiration.

**Comment by AnnuCode** [comment]
Hi @eneskaya , will it be the right approach if I use the  `ServerlessInstancesService` to collect all the Serverless instances in the specified project and then append them to a  Clusters slice which would then have all the clusters?

**Comment by eneskaya** [comment]
Hey @AnnuCode, you can use `ServerlessInstanceService` to collect the serverless instances, yes! But instead of appending them to the Clusters slice you can create a new function in the `serverlessinstances` package in Komiser. e.g.

```go
package serverlessinstances

func ServerlessInstances(ctx context.Context, client providers.ProviderClient) ([]models.Resource, error) {
    // Do the work
    return [...collected resources], nil
}
```

which would live in `providers/mongodbatlas/serverlessinstances/serverlessinstances.go`. 

Hope that helps, feel free to ping otherwise. And thanks for your interest in Komiser!

**Comment by AnnuCode** [comment]
@eneskaya Thanks for the detailed explanation. I'll do as mentioned to collect the serverless clusters. But regarding their cost calculation, at present I'm not sure how to get the read/write units which is essential to calculate the cost(as per the MongoDB docs). I'll look into it.

**Comment by eneskaya** [comment]
No problem, happy to help!

As for cost estimation, you could skip that in the first step. We do this for some services actually, as it can be quite tedious to calculate the costs correctly. Have a look around in some of the providers where we just pass `monthlyCost: 0`.
