### ISSUE TITLE
Link not working.

### ISSUE THREAD

**Issue by GenMech** [tailwarden/komiser#621]
**Describe the bug**
I was going through the contributors guidelines to start my journey of contribution to Komiser. But the link of discord given there is not working.
Lets have a look:
" We recommend discussing your plans on our Discord (join our **[community server](https://discord.oraculi.io/)**)" 
The hyper link added to "Community Server" is not working.

**To Reproduce**
You can give me an updated link and I will update in the "komiser/Contributing.md"

**Expected behavior**
So that people who are looking forward to contribute and wants to join the community can join to the server without any issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/85284840/225084111-66de74cb-99b4-4035-a920-f47e76bcdc89.png)

**Comment by GenMech** [comment]
@jakepage91 No worries!! Can you provide me an updated discord link (Make sure it has no time limit). I will update the changes and make a pull request

**Comment by jakepage91** [comment]
cheers yeah! You can add https://discord.tailwarden.com Appreciate it @GenMech

**Comment by GenMech** [comment]
@jakepage91 Done! PR #627
