### ISSUE TITLE
Duplicated Links in the Dashboard->Inventory Menu Left

### ISSUE THREAD

**Issue by jolo-dev** [tailwarden/komiser#644]
**Describe the bug**
There are duplicated links left on the inventory page.

**To Reproduce**
1. Run the frontend
2. Go to Inventory page

**Expected behavior**
Single links in the menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/54506108/226391356-86b0b978-e736-4d24-aed9-2f2bb7875e9f.png)

**Desktop (please complete the following information):**
 - Browser: Brave, Arc (Chromium based), Firefox

**Comment by eneskaya** [comment]
Hey @jolo-dev , thanks for the issue report! We address this in PR #678 :)

**Comment by jolo-dev** [comment]
@eneskaya cool! Good Job! Let me know when it's merged ;)

**Comment by eneskaya** [comment]
Hey @jolo-dev, It's merged in our `develop` branch and will go out as part of the weekly release on Friday!
