### ISSUE TITLE
Support GCP Certificates

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#668]
**Describe the solution you'd like**
Collect GCP Certificates data
**Additional context**
To get an idea of how to implement the collector, take the [GCP Compute](https://github.com/tailwarden/komiser/blob/master/providers/gcp/compute/compute.go) resource as inspiration.

**Comment by ShubhamPalriwala** [comment]
Hey, Can I give this a shot?

**Comment by mlabouardy** [comment]
> Hey, Can I give this a shot?

ofc, its yours
