### ISSUE TITLE
Support GCP Functions

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#669]
**Describe the solution you'd like**
Collect GCP Functions data
**Additional context**
To get an idea of how to implement the collector, take the [GCP Compute](https://github.com/tailwarden/komiser/blob/master/providers/gcp/compute/compute.go) resource as inspiration.

**Comment by jakepage91** [comment]
Hey there @ShubhamPalriwala I have a pretty intense (and short week) and proably won't have time to work on this would you like me to assign it to you?

**Comment by ShubhamPalriwala** [comment]
yes please, that'd be awesome!

**Comment by mlabouardy** [comment]
> yes please, that'd be awesome!

all yours then

**Comment by ShubhamPalriwala** [comment]
lets close this?
