### ISSUE TITLE
Support GCP Redis instances

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#673]
**Describe the solution you'd like**
Collect GCP Redis instances data
**Additional context**
To get an idea of how to implement the collector, take the [GCP Compute](https://github.com/tailwarden/komiser/blob/master/providers/gcp/compute/compute.go) resource as inspiration.

**Comment by ShubhamPalriwala** [comment]
Can I take this up too 😃?

**Comment by mlabouardy** [comment]
> Can I take this up too 😃?

ofc, assigned to you :)

**Comment by ShubhamPalriwala** [comment]
Hey, ran into a small query here, we can query the redis instances based on the region provided (the "global" param does not work here unlike Certs).

An approach that I can think of is, query all the locations and then make a request one by one for each location, however this might make it really heavy. Would like to know if you have encountered something like this before or maybe have a better way to tackle this?

**Comment by mlabouardy** [comment]
> Hey, ran into a small query here, we can query the redis instances based on the region provided (the "global" param does not work here unlike Certs).
> 
> An approach that I can think of is, query all the locations and then make a request one by one for each location, however this might make it really heavy. Would like to know if you have encountered something like this before or maybe have a better way to tackle this?

we had a similar problem with AWS, except for S3 which is a global endpoint, for other services we had to go through all regions and fetch services. I would suggest doing the same here, to get all locations and fetch instances for each region.
