### ISSUE TITLE
Support GCP SQL instances

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#674]
**Describe the solution you'd like**
Collect GCP SQL instances data
**Additional context**
To get an idea of how to implement the collector, take the [GCP Compute](https://github.com/tailwarden/komiser/blob/master/providers/gcp/compute/compute.go) resource as inspiration.

**Comment by ShubhamPalriwala** [comment]
Haha, can i this too next?

**Comment by mlabouardy** [comment]
> Haha, can i this too next?

ofc

**Comment by ShubhamPalriwala** [comment]
haha! pr has been opened sir xD

**Comment by mlabouardy** [comment]
> haha! pr has been opened sir xD

already, haha 🚀

**Comment by ShubhamPalriwala** [comment]
This can also be closed?

**Comment by mlabouardy** [comment]
> This can also be closed?

yes, thanks for reminder
