### ISSUE TITLE
Support GCP API Gateways

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#675]
**Describe the solution you'd like**
Collect GCP API Gateways data
**Additional context**
To get an idea of how to implement the collector, take the [GCP Compute](https://github.com/tailwarden/komiser/blob/master/providers/gcp/compute/compute.go) resource as inspiration.

**Comment by mlabouardy** [comment]
> Hey, this looks like the only pending GCP task on the roadmap currently that is unassigned, can i take this up?

its yours :)

**Comment by ShubhamPalriwala** [comment]
This can be closed in favour of #715
