### ISSUE TITLE
Invalid "Guide To Connect Account" Link

### ISSUE THREAD

**Issue by ShubhamPalriwala** [tailwarden/komiser#699]
**Describe the bug**
On running the Komiser binary locally with a default config file, Komiser asks to connect account. However, on clicking on that button, it takes to a page that sends back a 404 https://docs.komiser.io/docs/overview/introduction/getting-started/.

**To Reproduce**
1. Run Komiser locally without configuring anything
2. Click on the Guide To Connect Account

**Expected behavior**
Should point to the correct link

**Screenshots**
![Screenshot_2023-04-04-21-29-48_3000x1920](https://user-images.githubusercontent.com/55556994/229850175-eafc1e3b-7177-438e-bff3-d727beb7dce4.png)

On clicking:
![Screenshot_2023-04-04-21-30-14_3000x1920](https://user-images.githubusercontent.com/55556994/229850300-d0311eba-ea4c-4ccf-92b8-b78bd11d5b44.png)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser Chrome
```sh
❯ ./komiser version
INIT!!!
Komiser
 Version:         Unknown
 Go Version:      go1.20.2
 Commit:          Unknown
 OS/Arch:         linux/amd64
 Built:           Unknown
```

**Comment by mlabouardy** [comment]
Thanks @ShubhamPalriwala, do you want to push a fix for this? :)

**Comment by ShubhamPalriwala** [comment]
This can be closed now, thanks!
