### ISSUE TITLE
Onboarding Wizard

### ISSUE THREAD

**Issue by mlabouardy** [tailwarden/komiser#786]
**Is your feature request related to a problem? Please describe.**
Users can currently connect one or many cloud accounts from the nine supported cloud providers through a `config.toml` file. However, this requires users to have knowledge of config file syntax, as well as an understanding of what permissions they need to assign to Komiser in order for it to fetch their asset inventory. We have received numerous issues in our GitHub repository and Discord community regarding this process of connecting a cloud account.

**Describe the solution you'd like**
Having an onboarding wizard can help users connect their cloud accounts more easily because it provides a GUI that guides users through the process step-by-step. This can be more user-friendly and less intimidating than configuring accounts through a configuration file, which requires the user to have knowledge of the specific syntax and format of the file. Additionally, a wizard can help prevent Komiser's lack of permission errors.

**Comment by Kolawole99** [comment]
@mlabouardy assign this issue to me
