### ISSUE TITLE
Integrate OpenCost for Kubernetes clusters

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#801]
**Is your feature request related to a problem? Please describe.**
At the moment we don't have a way of fetching and displaying cost info for Kubernetes clusters and objects.

**Describe the solution you'd like**
By integrationg OpenCost into Komiser we can leverage the tool to fetch the cost data of the Kubernetes clusters that are configured in the Komiser config.toml file.

Links: 🔗 
OpenCost documentation: https://www.opencost.io/docs/

**Comment by Azanul** [comment]
May I take this up?

**Comment by shivam-sharma7** [comment]
@Azanul All yours:)

**Comment by Azanul** [comment]
@mlabouardy I think you closed this by mistake, the PR is still open.

**Comment by mlabouardy** [comment]
> @mlabouardy I think you closed this by mistake, the PR is still open.

just merged :)

**Comment by Azanul** [comment]
> > @mlabouardy I think you closed this by mistake, the PR is still open.
> 
> just merged :)
😂 I just deleted that seeing that you merged it
