### ISSUE TITLE
configured komiser connected to one AWS account but it shows two accounts in the dashboard

### ISSUE THREAD

**Issue by naisayer** [tailwarden/komiser#804]
Configured komiser with one AWS account connected but it shows two in the dashboard:

<img width="323" alt="Screenshot 2023-05-22 at 2 17 17 pm" src="https://github.com/tailwarden/komiser/assets/27228/ecf34a2e-bebe-4ad0-9a9f-e09c4416fc36">

I think due to all ec2 keypairs being assigned to a null account:

<img width="2120" alt="Screenshot 2023-05-22 at 2 18 09 pm" src="https://github.com/tailwarden/komiser/assets/27228/b08c2946-5e8e-464d-b805-52f8b3684667">

**Comment by naisayer** [comment]
Think due to account name missing here:

  https://github.com/tailwarden/komiser/blob/6145d7e7d4138c117668e975e2548ddab953b2ba/providers/aws/ec2/keypair.go#L37

**Comment by mlabouardy** [comment]
> Think due to account name missing here:
> 
> https://github.com/tailwarden/komiser/blob/6145d7e7d4138c117668e975e2548ddab953b2ba/providers/aws/ec2/keypair.go#L37

Good catch, merged the PR :)
