### ISSUE TITLE
AWS warnings

### ISSUE THREAD

**Issue by naisayer** [tailwarden/komiser#805]
Connected komiser to one AWS account, see the following warnings/errors:

[AWS] operation error Kinesis: ListShards, https response error StatusCode: 400, RequestID: fd33413c-adc1-a84f-a1d7-b69456d32a6a, InvalidArgumentException: Either NextToken, or one of StreamName and StreamARN should be provided.

[AWS] operation error ECS: ListTasks, https response error StatusCode: 400, RequestID: 96e7e314-4601-43f3-bf3e-c57448f42d31, ClusterNotFoundException: Cluster not found.

[AWS] operation error ECS: ListServices, https response error StatusCode: 400, RequestID: be2f3ef7-355d-4840-b15a-ed309fa3393d, ClusterNotFoundException: Cluster not found.

No active ECS or Kinesis in this account.

Have allow for these in the IAM policy:
  "ecs:List*"
  "kinesis:List*"

**Comment by mlabouardy** [comment]
address in https://github.com/tailwarden/komiser/pull/809
