### ISSUE TITLE
Calculate cost for GCP Compute Disks

### ISSUE THREAD

**Issue by PumpkinSeed** [tailwarden/komiser#807]
**Describe the solution you'd like**
Calculate cost for GCP Compute Disks

**Comment by PumpkinSeed** [comment]
> any update on this @PumpkinSeed, let me know if you need some help :)

I didn't have time to start on this yet, I did have a few other things on my list.

**Comment by PumpkinSeed** [comment]
I think it's been resolved in #853.

**Comment by mlabouardy** [comment]
> I think it's been resolved in #853.

Yes, thanks :)
