### ISSUE TITLE
Cost exporer never shows "daily view" graph

### ISSUE THREAD

**Issue by naisayer** [tailwarden/komiser#810]
Choose "daily view" on the dashboard.

The console shows a request to http://10.1.20.232/costs/explorer with request POST:

    '{"group":"service","granularity":"MONTHLY","start":"2023-04-01","end":"2023-04-30","exclude":[]}

Granularity is incorrectly set to "MONTHLY" should be "DAILY".

**Comment by addegbenga** [comment]
@mlabouardy  i will like to work on this.

**Comment by mlabouardy** [comment]
> @mlabouardy i will like to work on this.

all yours :)
