### ISSUE TITLE
Cost explorer requested date ranges are wrong

### ISSUE THREAD

**Issue by naisayer** [tailwarden/komiser#811]
Inspecting the request POST data to /costs/explorer.

Choose "Last 6 months" includes current month, but should be 2022-11-24 to 2023-05-24?

  {"group":"service","granularity":"MONTHLY","start":"2022-11-01","end":"2023-05-24","exclude":[]}

Choose "Last 3 months" doesn't include current month but should be 2023-08-24 to 2023-05-24?

  {"group":"service","granularity":"MONTHLY","start":"2023-02-01","end":"2023-04-30","exclude":[]}

Choose "Last 12 months" doesn't include current month should be 2022-11-24 to 2023-05-24?

{"group":"service","granularity":"MONTHLY","start":"2022-05-24","end":"2023-04-30","exclude":[]}

Be nice to have a date picker here too ?

**Comment by Azanul** [comment]
May I take this up?

**Comment by mlabouardy** [comment]
> May I take this up?

all yours 🔥

**Comment by Azanul** [comment]
I considered adding date pickers or date range widget but skipped it now for the lack of a design. Also, I don't trust myself in making things look good.
