### ISSUE TITLE
Support Linode Instance Volumes

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#815]
**Describe the solution you'd like**
Collect Linode Volumes
**Additional context**
To get an idea of how to implement the collector, take the [Compute Instances](https://github.com/tailwarden/komiser/blob/master/providers/linode/compute/instances.go) resource as inspiration.

**Comment by chetak123** [comment]
Hey @jakepage91 isn't this issue similar to https://github.com/tailwarden/komiser/issues/822 ?

**Comment by ShubhamPalriwala** [comment]
Hey @chetak123, great catch! thanks for the point out, will close this!
