### ISSUE TITLE
Support Linode Object storage bucket

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#820]
**Describe the solution you'd like**
Collect Linode Object Storage bucket
**Additional context**
To get an idea of how to implement the collector, take the [Compute Instances](https://github.com/tailwarden/komiser/blob/master/providers/linode/compute/instances.go) resource as inspiration.

**Comment by professorabhay** [comment]
Hai @jakepage91, I would Like to work on that.
Please assign it to me.

**Comment by professorabhay** [comment]
Hey @jakepage91 @ShubhamPalriwala, I found that there is a file already present which doing similar task.
[providers/linode/storage/buckets.go](https://github.com/tailwarden/komiser/blob/develop/providers/linode/storage/buckets.go)
Is there any misunderstanding??

**Comment by ShubhamPalriwala** [comment]
Hey @professorabhay, apologies for this! You are correct, we duplicated it from our end :(, I'll close this issue, thanks a lot for pointing it out! 💯
