### ISSUE TITLE
Support Linode Postgres Instances

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#821]
**Describe the solution you'd like**
Collect Linode Postgres Instances
**Additional context**
To get an idea of how to implement the collector, take the [Compute Instances](https://github.com/tailwarden/komiser/blob/master/providers/linode/compute/instances.go) resource as inspiration.

**Comment by ShubhamPalriwala** [comment]
Hey @professorabhay, now that you have the experience for adding the support for MySQL on Linode 💯, let's get this going too? let me know if i can assist in any way to make things easier for you :rocket:

**Comment by professorabhay** [comment]
Hey @ShubhamPalriwala, Would like to provide some resources that will helpful??

**Comment by ShubhamPalriwala** [comment]
Hey, it should be vv similar to the MySQL resource! You might just need to play around with a different method than the SQL one and to verify the Postgres pricing, you may refer to here: https://www.linode.com/products/postgresql/
