### ISSUE TITLE
Support Linode MySQL instances

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#823]
**Describe the solution you'd like**
Collect Linode MySQL instances
**Additional context**
To get an idea of how to implement the collector, take the [Compute Instances](https://github.com/tailwarden/komiser/blob/master/providers/linode/compute/instances.go) resource as inspiration.

**Comment by professorabhay** [comment]
Hai @jakepage91, I would like to work on it.
Please assign it to me. I wrote some code also

**Comment by jakepage91** [comment]
All yours @professorabhay!

**Comment by professorabhay** [comment]
Hai @jakepage91, To `Collect Linode MySQL instances` we need API key of the linode server.
I just wanna ask that the input of API key is by the user ??

**Comment by professorabhay** [comment]
Hey @jakepage91, I did my work.
Please take a look and let me know if you want any changes.
