### ISSUE TITLE
AWS accounts cost is overestimated

### ISSUE THREAD

**Issue by naisayer** [tailwarden/komiser#827]
AWS account cost is overestimated, because the cost calculations include ec2 instances which are in "stopped" state.

This is an issue in a a dynamic K8s cluster where nodes change state from "running" to "stopped" quite frequently.

Quick fix would be to check ec2 instance state and mark as off on the komiser db?

Longer term fix, would be to use the AWS CE API to get actual costs rather than try to estimate based on resources?

**Comment by mlabouardy** [comment]
> AWS account cost is overestimated, because the cost calculations include ec2 instances which are in "stopped" state.
> 
> This is an issue in a a dynamic K8s cluster where nodes change state from "running" to "stopped" quite frequently.
> 
> Quick fix would be to check ec2 instance state and mark as off on the komiser db?
> 
> Longer term fix, would be to use the AWS CE API to get actual costs rather than try to estimate based on resources?

Thanks for reporting the issue @naisayer 
If you up to it, you can push a quick fix [here](https://github.com/tailwarden/komiser/blob/master/providers/aws/ec2/instances.go#L126) by checking if the instance status is running before calculating the cost :)

**Comment by naisayer** [comment]
PR done.

**Comment by mlabouardy** [comment]
> PR done.

Thanks, it will be released in v3.0.18 (in Friday)

**Comment by naisayer** [comment]
Thanks.
