### ISSUE TITLE
Filters bar & filters style don't match the designs

### ISSUE THREAD

**Issue by mlabouardy** [tailwarden/komiser#841]
**Describe the bug**

Currently, the filters look like a button variation (because of the size) and blend into the background, looking like a cut in the layout (because of the background color).

I assume that the height of the filter was made bigger to match the button style of "Clear filters", but in this case I would suggest using the text button approach and keeping the styling of the tag different from the button.

Current implementation:

![image](https://github.com/tailwarden/komiser/assets/10320205/1b4d63b4-6d64-42fc-979f-92bb11bd2312)

Figma reference:

![image](https://github.com/tailwarden/komiser/assets/10320205/8432de01-b240-48e9-ad1a-c65fb585f81d)

**Additional context**
If you want to tackle this task, feel free to share with us your email address so we can give you access to the Figma project :)

<sub>[TECH-1281](https://linear.app/tailwarden/issue/TECH-1281/filters-bar-and-filters-style-dont-match-the-designs)</sub>

**Comment by shobhitexe** [comment]
Hey you can assign this to me i would love to work on this

**Comment by jakepage91** [comment]
Assigned, I'll let @mlabouardy add you to Figma

**Comment by mlabouardy** [comment]
> Assigned, I'll let @mlabouardy add you to Figma

Done :)
