### ISSUE TITLE
Update toast to match Figma design

### ISSUE THREAD

**Issue by mlabouardy** [tailwarden/komiser#843]
**Describe the bug**

The text size should be different for the title and the description to reflect the hierarchy of information. There should be a bigger padding between the title and the description.

The icon should be aligned with the title so that it doesn't move from one toast notification to the other - only the height would change depending on the length of the description.

Current implementation:

![image](https://github.com/tailwarden/komiser/assets/10320205/7996ec8a-07c9-4246-81fe-0ca2783b742b)

Figma reference:

![image](https://github.com/tailwarden/komiser/assets/10320205/5b08e039-9240-4a34-a2eb-d8db8009fdeb)

**Additional context**
If you want to tackle this task, feel free to share with us your email address so we can give you access to the Figma project :)

**Comment by CYBWEBALI** [comment]
Hey,I can work on this issue. Can u assign it to me?

**Comment by ShubhamPalriwala** [comment]
Sure @CYBWEBALI, could you share your email ID over so that we can invite you to the figma file so that you can take a look at the exact dimensions? Once we do that, and you confirm the access to figma, we'll assign the issue and get going!

**Comment by mlabouardy** [comment]
> Hello Mohammed. Pls can you assign this to me?
> 
> my email address is [iamoluwaseyiolasupo@gmail.com](mailto:iamoluwaseyiolasupo@gmail.com). Thank you so much

Hey @Oluwaseyi3, any update on this issue, were you able to access Figma?

**Comment by Oluwaseyi3** [comment]
Yes. I’m pushing the code in the next 10 mins. I’ve already fixed the issue
