### ISSUE TITLE
Set max character length with ellipsis for resources tags

### ISSUE THREAD

**Issue by mlabouardy** [tailwarden/komiser#844]
**Describe the bug**
![image](https://github.com/tailwarden/komiser/assets/10320205/f79e8610-d9c2-4f2f-bb70-0f3146947efd)

**Comment by osesantos** [comment]
hey @mlabouardy I would like to take this issue.

**Comment by RIYASANVI7** [comment]
please assign issue to me

**Comment by mlabouardy** [comment]
> 

all yours :) FYI,  we need to set 320px of max-width and a 2 lines maximum for height when it comes to content

**Comment by RIYASANVI7** [comment]
may you please elaborate the information that what actually has to be done

**Comment by ShubhamPalriwala** [comment]
Hey @RIYASANVI7, so as you can see in the screenshot attached above in the issue description, the tags take up a lot of space as they do not have any css fields such as `max-width` or number of lines for `max-height`.
What you could do is try to play around the values that are provided above in terms of pixels and lines of the tag hover component and see if you could limit it to the same.

If you need any more help, hop on to our Discord and we'll try to help in any way we can!

**Comment by RIYASANVI7** [comment]
Hello @ShubhamPalriwala sir, i have tried some modifications at my end, please check if it will work out or not. 
 
I am working on it.
 https://github.com/RIYASANVI7/komiser/blob/develop/README.md
kindly check at the bottom of file.

**Comment by ShubhamPalriwala** [comment]
Hey @RIYASANVI7, I would recommend you to watch this video about how one can start contributing to the dashboard of Komiser: https://www.youtube.com/watch?v=uwxj11-eRt8

It should really give you headstart

**Comment by knav33n** [comment]
May I pick this up?

**Comment by mlabouardy** [comment]
> May I pick this up?

all yours @knav33n :)

**Comment by knav33n** [comment]
Hi @mlabouardy, I have raised a pr for this issue and it looks like I have conflicts with dashboard/package-lock.json file. I could really benefit from some help on how to proceed.
