### ISSUE TITLE
Exclude component + dropdown doesn't match the design

### ISSUE THREAD

**Issue by mlabouardy** [tailwarden/komiser#845]
**Describe the bug**
Current implementation:
![image](https://github.com/tailwarden/komiser/assets/10320205/3b71fe13-9e83-4edb-8c46-c1bf6c01956f)

Figma reference:
![image](https://github.com/tailwarden/komiser/assets/10320205/97af4af7-8efd-48f0-a3fa-8b52fe223c6f)

**Additional context**
If you want to tackle this task, feel free to share with us your email address so we can give you access to the Figma project :)

**Comment by MouradGaa** [comment]
Hello @mlabouardy, I can work on this task 😊
email: mourad.gaaloul99@gmail.com

**Comment by MouradGaa** [comment]
So, apart from changing the design, the "Apply" button should also be removed and the filtering happens right upon selecting a checkbox?

**Comment by mlabouardy** [comment]
> So, apart from changing the design, the "Apply" button should also be removed and the filtering happens right upon selecting a checkbox?

exactly :)

**Comment by mlabouardy** [comment]
> > So, apart from changing the design, the "Apply" button should also be removed and the filtering happens right upon selecting a checkbox?
> 
> exactly :)

I just saw your implementation, we can go with your proposal for now :)
