### ISSUE TITLE
Bulk actions bar style doesn't match design

### ISSUE THREAD

**Issue by mlabouardy** [tailwarden/komiser#847]
**Describe the bug**
Since we're implementing the hiding action and changing the component for bulk actions, I would recommend adapting the design to match the source of truth. With the current implementation, there are 3 visual indicators of the resources selected, which can be distracting since we can usually process a max of 7 elements at a time.

Current implementation:
![image](https://github.com/tailwarden/komiser/assets/10320205/2ddbe0e2-fc54-43f8-a817-7a083addaaca)

Figma:
![image](https://github.com/tailwarden/komiser/assets/10320205/302c6378-0104-4ca3-88d6-d365af52ca5b)

**Additional context**
If you want to tackle this task, feel free to share with us your email address so we can give you access to the Figma project :)

**Comment by addegbenga** [comment]
Please assign this issue to me.

**Comment by addegbenga** [comment]
> It's yours @addegbenga!
Thank you can you add me to the figma my email: addegbenga@gmail.com

**Comment by mlabouardy** [comment]
> > It's yours @addegbenga!
> > Thank you, can you add me to the figma my email: [addegbenga@gmail.com](mailto:addegbenga@gmail.com)

done :)
