### ISSUE TITLE
Update Komiser AWS IAM Policy

### ISSUE THREAD

**Issue by ShubhamPalriwala** [tailwarden/komiser#852]
**Describe the bug**
The current [policy.json](https://github.com/tailwarden/komiser/blob/master/policy.json) has a lot of wildcards and also lacks a few resources that we have started to support lately.

**To Reproduce**
Add this Policy to an IAM role and run komiser with that role, and you would see a few fetch permissions errors

**Expected Behavior**
The policy should be:
- Granular (ie no wildcards, we only need to read the resource metadata)
- Have exactly each resource we support (no less no more)

**Possible Plan of Action**
- Create a policy from scratch (possibly with the latest AWS policy format)
- Go through each of the resources we query
- Add the Read Access for that resource
- Test it thoroughly and make sure NO errors are seen in the console due to policy

For any help/doubts, feel free to comment here or even hop on to our [Discord](https://discord.tailwarden.com/)!
This feature would really help us in the project's security and UX!

**Comment by ShubhamPalriwala** [comment]
Hey @professorabhay sure! 
Do checkout this video from @jakepage91 on how to start contributing: https://youtu.be/Vn5uc2elcVg

Feel free to ping me here or on our [Discord](https://discord.tailwarden.com/) server!

**Comment by professorabhay** [comment]
Hi @ShubhamPalriwala, I look into that issue and trying to resolve it....
I have a solution for that is I've replaced the wildcards with specific actions for each supported resource.
