### ISSUE TITLE
Error with DigitalOcean resource

### ISSUE THREAD

**Issue by hacKarim** [tailwarden/komiser#863]
**Describe the bug**

**To Reproduce**
1. komiser init
2. komiser start

**Error**

NIT!!!
INFO[2023-06-21T00:46:23+01:00] Debug logging is enabled
INFO[2023-06-21T00:46:23+01:00] Data will be stored in SQLite
INFO[2023-06-21T00:46:23+01:00] migrated to group #1 (20230413100000, 20230602100000)
INFO[2023-06-21T00:46:23+01:00] Komiser version: 3.0.19, commit: c4100e93939901f100f522f5a2e3baeb06bc2c30, buildt: 1686914094
INFO[2023-06-21T00:46:23+01:00] Fetching resources workflow has started
INFO[2023-06-21T00:46:23+01:00] Fetched resources                             account=demo-account provider=DigitalOcean
 resources=1 service=Droplet
INFO[2023-06-21T00:46:24+01:00] Fetched resources                             account=demo-account provider=DigitalOcean
 resources=1 service=Firewall
INFO[2023-06-21T00:46:24+01:00] Fetched resources                             account=demo-account provider=DigitalOcean
 resources=0 service="Load Balancer"
INFO[2023-06-21T00:46:25+01:00] Fetched resources                             account=demo-account provider=DigitalOcean
 resources=1 service=VPC
INFO[2023-06-21T00:46:25+01:00] Fetched resources                             account=demo-account provider=DigitalOcean
 resources=0 service=Kubernetes
INFO[2023-06-21T00:46:26+01:00] Fetched resources                             account=demo-account provider=DigitalOcean
 resources=2 service=Database
INFO[2023-06-21T00:46:27+01:00] Fetched resources                             account=demo-account provider=DigitalOcean
 resources=0 service=Trigger
INFO[2023-06-21T00:46:27+01:00] Fetched resources                             account=demo-account provider=DigitalOcean
 resources=1 service=Namespace
INFO[2023-06-21T00:46:27+01:00] Fetched resources                             account=demo-account provider=DigitalOcean
 resources=0 service=Volume
ERRO[2023-06-21T00:46:27+01:00] error fetching DigitalOcean resources         err="<nil>"

**Comment by professorabhay** [comment]
Hey @hacKarim, I would like to give you some suggestions. 

- Verify DigitalOcean API credentials
- Update Komiser
