### ISSUE TITLE
Move AutoScalingGroupClient from autoscaling_groups_client.go to autoscaling_groups.go

### ISSUE THREAD

**Issue by ShubhamPalriwala** [tailwarden/komiser#872]
**Describe the bug**
We right now define a type interface AutoScalingGroupClient in a file and no other use case is there, it would be a cleaner approach to move it to the core `autoscaling_groups.go` file for easier code readability.

**Additional context**
- Original file from where the type is to be moved:
https://github.com/tailwarden/komiser/blob/develop/providers/aws/ec2/autoscaling_groups_client.go

- File the type should be moved to:
https://github.com/tailwarden/komiser/blob/develop/providers/aws/ec2/autoscaling_groups.go

**Comment by alexandreliberato** [comment]
I can work on this.
