### ISSUE TITLE
Add Cost Calculation for AWS CloudFront Distributions

### ISSUE THREAD

**Issue by ShubhamPalriwala** [tailwarden/komiser#877]
We support the AWS CloudFront Distribution resource [here](https://github.com/tailwarden/komiser/blob/develop/providers/aws/cloudfront/distributions.go) but we do not do cost calculations for it. It would be really good to calculate the cost for accurate reportings! 

You can build an algorithm for pricing from here: https://aws.amazon.com/cloudfront/pricing/

**Comment by bishal7679** [comment]
is this issue resolved?? If not then assign it to me
@jakepage91 @mlabouardy

**Comment by AvineshTripathi** [comment]
all yours!

**Comment by jakepage91** [comment]
Thanks @bishal7679

**Comment by bishal7679** [comment]
I am gonna work on this again using cost explorer!
