### ISSUE TITLE
Add Cost Calculation for AWS Cloudwatch Log Metrics

### ISSUE THREAD

**Issue by ShubhamPalriwala** [tailwarden/komiser#878]
We support the AWS Cloudwatch Log Metric resource [here](https://github.com/tailwarden/komiser/blob/develop/providers/aws/cloudwatch/log_metrics.go) but we do not do cost calculations for it. It would be really good to calculate the cost for accurate reportings!

You can build an algorithm for pricing from here:
- https://aws.amazon.com/cloudwatch/pricing/
- https://www.vantage.sh/blog/cloudwatch-metrics-pricing-explained-in-plain-english (this is slightly old but can be used as an inspiration)

**Comment by Azanul** [comment]
May I take this up?
@ShubhamPalriwala @mlabouardy

**Comment by mlabouardy** [comment]
> May I take this up? @ShubhamPalriwala @mlabouardy

all yours :)
