### ISSUE TITLE
Integrate Go linter to GitHub Actions

### ISSUE THREAD

**Issue by mlabouardy** [tailwarden/komiser#890]
**Is your feature request related to a problem? Please describe.**
After integrating [golangci-lint](https://github.com/golangci/golangci-lint) into [Komiser CI/CD](https://github.com/tailwarden/komiser/blob/develop/.github/workflows/build_test_pr.yml#L40) we realized that the action takes a lot of time and runs into timeout after 5mins.

**Comment by mlabouardy** [comment]
> I will check this one @mlabouardy

assigned, thanks :)

**Comment by asamirr** [comment]
Do we need to fix golangci-lint or are we open to using different ones? I was messing around with my fork and tried https://github.com/marketplace/actions/go-linter and I think it works. A bit too aggressive with its checks though. Check my run here https://github.com/asamirr/komiser/actions/runs/6448262872/job/17505336578

**Comment by Azanul** [comment]
> Do we need to fix golangci-lint or are we open to using different ones? I was messing around with my fork and tried [Go-lint](https://github.com/marketplace/actions/go-linter) and I think it works. A bit too aggressive with its checks though. Check my run [here](https://github.com/asamirr/komiser/actions/runs/6448262872/job/17505336578)

I think we should stick with golangci-lint, since it is the standard.

**Comment by Azanul** [comment]
I think this has already been resolved
