### ISSUE TITLE
The filters icons doesn't match design

### ISSUE THREAD

**Issue by mlabouardy** [tailwarden/komiser#892]
**Describe the bug**
The icons are mismatched with each other in terms of style and stroke weight (especially the add button).
![image](https://github.com/tailwarden/komiser/assets/10320205/c0f2bcd8-fe6e-48d4-9c69-5f292b677c07)
![image](https://github.com/tailwarden/komiser/assets/10320205/5c3e5e43-b3de-48a0-a811-1012144aabdc)

The filter preview inside the adding filter container shouldn't be full width:
![image](https://github.com/tailwarden/komiser/assets/10320205/c631c6b2-1cbd-4c48-86bd-f275ffb940fa)

The hover interaction is missing from the buttons (documented on the Figma file, I recommend using the Dev mode to interact with the components).

The spacing inside the filter is too big.

![image](https://github.com/tailwarden/komiser/assets/10320205/ca45c809-72f3-426b-b55d-0721c48a8793)
![image](https://github.com/tailwarden/komiser/assets/10320205/69fcc7b5-1912-4e66-a6f5-101cbe50a7c2)

The ‘clear filters’ needs to be updated and I still recommend the text button approach.
![image](https://github.com/tailwarden/komiser/assets/10320205/bee4f785-591b-4550-9957-84fd1a8c4d4f)
![image](https://github.com/tailwarden/komiser/assets/10320205/feef3572-9af4-4cd8-99b5-038ae49dd443)

**Additional context**
If you want to tackle this task, feel free to share with us your email address so we can give you access to the Figma project :)

**Comment by shobhitexe** [comment]
hey willing to take this one can you plz assign it to me 

Figma mail : sguptamds94@gmail.com

**Comment by mlabouardy** [comment]
> hey willing to take this one can you plz assign it to me
> 
> Figma mail : [sguptamds94@gmail.com](mailto:sguptamds94@gmail.com)

done :)
