### ISSUE TITLE
Improve filters bar to match design

### ISSUE THREAD

**Issue by mlabouardy** [tailwarden/komiser#893]
**Describe the bug**
We should avoid the two filter buttons situation currently in production (add a button next to existing filters and the "filter by" at the top right) — there should be only one.

Implementation:
![image](https://github.com/tailwarden/komiser/assets/10320205/01fa19ee-16da-4f25-80e1-3f75e2b85d41)
Figma reference:
![image](https://github.com/tailwarden/komiser/assets/10320205/6a141a1f-19c9-489a-8503-f70b130ff877)

**Additional context**
If you want to tackle this task, feel free to share with us your email address so we can give you access to the Figma project :)

**Comment by azgcloudev** [comment]
@mlabouardy I can try to work this, tiazg95@gmail.com for the Figma access

**Comment by azgcloudev** [comment]
I see that current implementation is the same of the figma reference

<img width="1128" alt="image" src="https://github.com/tailwarden/komiser/assets/72358828/a95e2d79-78f8-4627-b9f2-b0398752be2b">

**Comment by AllieMendes** [comment]
As azgcloudev has mentioned, it seems like the implementation already covers this scenario thanks to this issue: https://github.com/tailwarden/komiser/issues/895
I believe we can close this ticket @mlabouardy
