### ISSUE TITLE
Move "Filter by" to filter bar

### ISSUE THREAD

**Issue by mlabouardy** [tailwarden/komiser#894]
**Describe the bug**
Implementation:
![image](https://github.com/tailwarden/komiser/assets/10320205/028a91f4-e781-4d57-9814-7f78b69c00b5)
Figma reference:
![image](https://github.com/tailwarden/komiser/assets/10320205/7037f6a6-5243-4915-8be0-c4d07427e9d4)
![image](https://github.com/tailwarden/komiser/assets/10320205/7c4f7421-23c4-4c9a-93ea-f6383fc999e8)

**Additional context**
If you want to tackle this task, feel free to share with us your email address so we can give you access to the Figma project :)

**Comment by shobhitexe** [comment]
Hey would like to take this you can assign this to me 

Figma mail : sguptamds94@gmail.com

**Comment by mlabouardy** [comment]
> Hey would like to take this you can assign this to me
> 
> Figma mail : [sguptamds94@gmail.com](mailto:sguptamds94@gmail.com)

all yours :)
