### ISSUE TITLE
Move 'Save as a view' to the filter bar

### ISSUE THREAD

**Issue by mlabouardy** [tailwarden/komiser#895]
**Describe the bug**
Implementation:
![image](https://github.com/tailwarden/komiser/assets/10320205/e1e0ba46-5536-4a2f-836e-dcb86552e82b)
Figma reference:
![image](https://github.com/tailwarden/komiser/assets/10320205/135a16e5-cb53-4e46-8ff6-eed2edc22b82)

**Additional context**
If you want to tackle this task, feel free to share with us your email address so we can give you access to the Figma project :)

**Comment by shobhitexe** [comment]
Hey, I would like to take this plz assign this to me 
my figma mail : sguptamds94@gmail.com
