### ISSUE TITLE
AWS load balancer Link is not working as intended

### ISSUE THREAD

**Issue by pavangudiwada** [tailwarden/komiser#914]
**Describe the bug**
The Link in the Load balancer page does not take you to the Load Balancer UI on AWS Console

**To Reproduce**
1. Build and run the current Develop branch
2. Go to Inventory -> All resources -> Filter -> Cloud service -> is -> ELB
3. Click one of the Load Balancers and click the link beside the Load Balancer's name.

**Expected behavior**
When the link is clicked, you should be taken to the specific Load Balancer details page on AWS console.

**Screenshots**
![image](https://github.com/tailwarden/komiser/assets/25551553/26f952cb-7cfe-4a31-b735-198771600ad2)

**Additional context**
In the screenshot above, 
1. The link should take you to the appropriate AWS Load Balancer
2. But the link has an extra **/** after **#** and this breaks the URL.

**Comment by AvineshTripathi** [comment]
Thanks @pavangudiwada for opening the issue would you like to open up PR to solve this?

**Comment by pavangudiwada** [comment]
@AvineshTripathi 
#915 Done :heavy_check_mark:
