### ISSUE TITLE
Cloud Openstack

### ISSUE THREAD

**Issue by ccroliv** [tailwarden/komiser#916]
Hello, is there any forecast for compatibility with Openstack?

**Comment by jakepage91** [comment]
Hey there @ccroliv we don't have Openstack on the roadmap but let me put it to the team and see if this could make sense! Cheers! Will get back to you shortly and sorry for the late reply.

**Comment by ndjones** [comment]
Hi, just checking in here if that new issue was visible to track progress on this work?
