### ISSUE TITLE
Add Dependaboat

### ISSUE THREAD

**Issue by shivam-sharma7** [tailwarden/komiser#924]
There are bunch of the dependecies who is older now and adding dependabot for the dashbord to manage our dependencies upgrades.

@AvineshTripathi WDYT?

**Comment by AvineshTripathi** [comment]
I think that is a good feature to have! Would you like to take this one?

**Comment by shivam-sharma7** [comment]
yes!

**Comment by AvineshTripathi** [comment]
I would suggest you to first do a proper explore where you try to note down detailed information about the bot and other alternatives, keeping in mind that the solution we take is easily maintainable and fullfils all our usecases!
