### ISSUE TITLE
Create a practical guide on how to use the webhook alerts integration and add it to Komiser docs

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#947]
**Is your feature request related to a problem? Please describe.**
Create a hand on's real use-case guide in which a solution is presented using the alerts webhook integration and add it to the guide section in the Komiser docs to showcase the possibility of how the webhook integration can be used, possible use cases: 

Komiser alert triggers ==> event on zapier ==> send email to admin ==> created a ticket on linear
Komiser alert triggers ==> lambda function is triggered ==> action is taken in AWS
Komiser alert triggers ==> pagerduty alert is triggered ==> post-mortem docs in created from template on notion

**Comment by akshayamadhuri** [comment]
@jakepage91  do we need to write a blog on it

**Comment by jakepage91** [comment]
Hey there @akshayamadhuri, not so much a blog post, it could be a shorter guide similar to this one https://docs.komiser.io/guides/alerts to include in the `Guide` section of the documentation. 
If you wanted to write a blog post too, then I'm guessing it would be easily convertible to a guide. Here is an example of a blog post I wrote on the topic of custom webhooks https://www.tailwarden.com/blog/komiser-introduces-custom-webhooks-feature

**Comment by akshayamadhuri** [comment]
@jakepage91 will be working on it

**Comment by jakepage91** [comment]
Great, All yours @akshayamadhuri !

**Comment by akshayamadhuri** [comment]
@jakepage91  can you please assist me should i add another sub topic as possible use cases in the Komiser guide  with these three use cases:
Komiser alert triggers ==> event on zapier ==> send email to admin ==> created a ticket on linear
Komiser alert triggers ==> lambda function is triggered ==> action is taken in AWS
Komiser alert triggers ==> pagerduty alert is triggered ==> post-mortem docs in created from template on notion

**Comment by jakepage91** [comment]
Oh these were just suggestions, but feel free to come up with another combination of tools that you feel like exploring in the guide. Up to you @akshayamadhuri. Thanks!

**Comment by akshayamadhuri** [comment]
`@jakepage91`  thanks

**Comment by akshayamadhuri** [comment]
**@jakepage91** Do we have a Slack community in Komiser
