### ISSUE TITLE
Update page link component to match Figma

### ISSUE THREAD

**Issue by AllieMendes** [tailwarden/komiser#948]
**Description**
Currently, the pages links implementation doesn't match the design, especially when it comes to hover and active states.
Let's align the implementation with the design.

**Implementation**
![image](https://github.com/tailwarden/komiser/assets/125025039/2d1cb1bc-964d-45f2-a7dd-4666c28652f0)

**Design**
![image](https://github.com/tailwarden/komiser/assets/125025039/f21544da-7db6-44c2-b163-3874d1204598)

Let us know if you'd like to work on this issue so we can invite you to the Figma project (link the email you'd like us to use).

**Comment by jakepage91** [comment]
Hey there @AllieMendes so it doesn't seem to be a way that I can find at least to add the small color styling on the left hand side of the sidebar component that's being hovered over. Have you seen this in other Mintlify built docs? If you please send it over. 

And additionally the color change in the background on the sidebar has to do with the size of the screen that the docs are being shown on, the sidebar seems to adapt differently as compared to the sidebar keys. I don't think there is anything that can be done here either.
