### ISSUE TITLE
Sync styling on info blocks

### ISSUE THREAD

**Issue by AllieMendes** [tailwarden/komiser#949]
**Description**
Currently, the info blocks styling is close but doesn't match the design, being a little out of branding and making it hard to understand code spans and links inside them.
Let's align the implementation with the design.

**Implementation**
![Pasted Graphic](https://github.com/tailwarden/komiser/assets/125025039/ce8a8a24-b267-44f2-bda3-aef25e24c09f)

**Design**
![image](https://github.com/tailwarden/komiser/assets/125025039/4f298f42-b92a-4714-8a58-308acbf94277)

Let us know if you'd like to work on this issue so we can invite you to the Figma project (link the email you'd like us to use).

**Comment by shobhitexe** [comment]
Hey would like to take this 

My figma mail : sguptamds94@gmail.com

**Comment by AllieMendes** [comment]
> Hey would like to take this
> 
> My figma mail : [sguptamds94@gmail.com](mailto:sguptamds94@gmail.com)

Hi there
I've invited you to the Figma project and tagged you on the component, let me know if there's anything else I can help with!

**Comment by shobhitexe** [comment]
Hello, I have a quick question about editing Mintlify default components. I've read the Mintlify documentation, which appears to be the basis for the Komiser documentation. We are currently using Mintlify's default <info> component for the above blocks, and from my research, it seems that it's not editable. Could you please help confirm whether it is possible to edit this component or not? if yes plz guide me how and if no any other alternatives such as using <div> and styling it?  Thank you

**Comment by AllieMendes** [comment]
Hi @shobhitexe!
@jakepage91 has set up those blocks, so he would probably know the answer to this better than me
Do you have any idea Jake?

I believe at least the code-span components should be customizable, from what I saw of other Mintlify docs

**Comment by jakepage91** [comment]
Hey there @shobhitexe here is an example of a project with non default icon colors https://github.com/loopholelabs/frpc-go/blob/staging/docs/mint.json maybe it can serve as inspirations since I wasn't able to find much info on the icon colors on the mintlify site itself

This is there docs site: https://frpc.io/introduction

**Comment by shobhitexe** [comment]
Hello , I believe the components that originate from Mintlify, such as the <Note> and <Tip> components which we are using in this case , are not customizable in terms of their styles. As we can observe in the example you provided, they are also using the <Note> component and its style not aligning with their overall design colors 

![image](https://github.com/tailwarden/komiser/assets/29349136/81d88e70-8b71-4285-a3f6-51a98c288e73)
![image](https://github.com/tailwarden/komiser/assets/29349136/69c63747-92e9-44ae-a763-d4ea12372dc3)

**Comment by jakepage91** [comment]
I'm going to do some further investigation and I'll let you know shortly 👍

**Comment by jakepage91** [comment]
Yeah you are right! It doesn't look like there is a way of editing the components referenced above. We will have to keep the styling as is and close this ticket. 

Thanks for looking into this @shobhitexe 👍
