### ISSUE TITLE
[Komiser docs] Implement styling on social media icons

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#952]
The social media icons, on the left nav column, don't have the styling projected on the Designs and have instead a color which doesn't match the Komiser branding.

Let's align the implementation with the design.

Implementation 
![styling-implementation](https://github.com/tailwarden/komiser/assets/38757612/1f056e3d-58cb-41a8-ad2d-8c8ef16f1c77)

Design
<img width="289" alt="desing-icon" src="https://github.com/tailwarden/komiser/assets/38757612/41012f56-b28e-4d08-89a2-dafe4bc4d758">

https://www.figma.com/file/1TQ0gUbs0rdmPgeyurWGWw/Komiser-Docs-revamp-(Aug-2023)?type=design&node-id=612%3A14144&mode=dev

**Comment by akshayamadhuri** [comment]
@jakepage91 i would like to contribute

**Comment by Oluwaseyi3** [comment]
Hi Jake. You can assign this asap to me

**Comment by mlabouardy** [comment]
> Hi Jake. You can assign this asap to me @jakepage91

all yours :)

**Comment by AllieMendes** [comment]
Can you please confirm the email so I can accept the request to see the file/invite you to Figma @Oluwaseyi3?

**Comment by shivam-sharma7** [comment]
@Oluwaseyi3 are you working?

**Comment by Oluwaseyi3** [comment]
> Can you please confirm the email so I can accept the request to see the file/invite you to Figma @Oluwaseyi3?

Okay @AllieMendes.

**Comment by Oluwaseyi3** [comment]
> @Oluwaseyi3 are you working? if you don't mind, I have a PR for this.
> 
> WDYT @jakepage91?

I haven't begun yet. I'm currently working on portion of the onboarding wizard. But I would finish this issue before the week is over

**Comment by jakepage91** [comment]
Hey there team! While working on another issue and found how to change the anchor colors too (without the gradient unfortunately) but at least the color is Komiser gray now. 

https://docs.komiser.io/welcome/overview

And since those changes were committed we can close this issue too! Thanks for looking into it @Oluwaseyi3 and @shivam-sharma7

**Comment by jakepage91** [comment]
Allie is off @Oluwaseyi3 but let me see if I can give you access to the figma doc, just a sec

**Comment by Oluwaseyi3** [comment]
> Hey there team! While working on another issue and found how to change the anchor colors too (without the gradient unfortunately) but at least the color is Komiser gray now.
> 
> https://docs.komiser.io/welcome/overview
> 
> And since those changes were committed we can close this issue too! Thanks for looking into it @Oluwaseyi3 and @shivam-sharma7

All right @jakepage91
