### ISSUE TITLE
[Komiser Docs] Implement styling on cards

### ISSUE THREAD

**Issue by jakepage91** [tailwarden/komiser#953]
Description

The cards acting as shortcuts to pages don't match the styling projected on the Designs — the icons should be in the Komiser gradient, the line height & size on the description text, the background color (on default & on hover state) and the stroke color (on default & on hover state).

Let's align the implementation with the design.

Implementation
![implement-card-design](https://github.com/tailwarden/komiser/assets/38757612/45aae44b-0ddc-4363-b685-4ba8b379b484)

Design
<img width="724" alt="design-card-design" src="https://github.com/tailwarden/komiser/assets/38757612/5deb2b76-1ab9-4c39-954e-005a00f00f67">

https://www.figma.com/file/1TQ0gUbs0rdmPgeyurWGWw/Komiser-Docs-revamp-(Aug-2023)?type=design&node-id=627%3A15118&mode=dev

**Comment by shivam-sharma7** [comment]
@jakepage91 I'm working on this and this my progress, I'm seeking for styling for this component where i implement further

![image](https://github.com/tailwarden/komiser/assets/91419219/ee3b432e-ecdb-47ed-9a11-ae029cfab85b)

**Comment by jakepage91** [comment]
Looks good @shivam-sharma7 but this issue has been merged already! 
Let me know if you would like me to find you another doc related issue. Always feel free to reach out on Discord.
