### ISSUE TITLE
Links in the Docs Introduction page lead to the same page. 

### ISSUE THREAD

**Issue by pavangudiwada** [tailwarden/komiser#965]
**Describe the bug**
All the links in https://docs.komiser.io/getting-started/introduction page have an extra /doc/ in the beginning and are leading no where. 

**To Reproduce**
1. Open https://docs.komiser.io/getting-started/introduction
2. Click any link  and you will be taken to https://docs.komiser.io/welcome/overview

**Expected behavior**
Take me to the page the guide points me to.

**Screenshots**
![image](https://github.com/tailwarden/komiser/assets/25551553/14830d61-f1ef-41ec-a984-9d02fcbd8d87)

**Comment by akshayamadhuri** [comment]
@pavangudiwada  i made the PR on this can you please review it

**Comment by pavangudiwada** [comment]
Hey @akshayamadhuri I can't review them, someone from the Komiser team will do that. Feel free to ask in the contributors channel on Komiser Discord.

**Comment by mlabouardy** [comment]
@jakepage91 can you check this please :)

**Comment by jakepage91** [comment]
Thanks for this @pavangudiwada, I just opened this [PR](https://github.com/tailwarden/komiser/pull/978) to address the issues.
