### ISSUE TITLE
paths are ignored by one of your .gitignore files

### ISSUE THREAD

**Issue by shivam-sharma7** [tailwarden/komiser#966]
**Describe the bug**
I was trying to `git add mint.json` file inside the docs dir and got following error.

```
PS C:\Users\shivam sharma\Desktop\My Project\open-source\komiser\docs> git add mint.json
The following paths are ignored by one of your .gitignore files:
docs
```
**To Reproduce**
 

**Expected behavior**
It should allow to add file

**Desktop (please complete the following information):**
 - OS: [Windows]
 

**Additional context**
we need to remove `docs/` dir from `.gitignore` file then it will allow to do that.

**Comment by shivam-sharma7** [comment]
@mlabouardy by default you got assigned but you can assign me if want so. :)

**Comment by AvineshTripathi** [comment]
All yours @shivam-sharma7 /

Also @mlabouardy should change the auto assign
